#pragma once
#include <stdio.h>
#include "structures.h"
#include "MyStructures.h"
#include "DefTomb4Funct.h"

namespace trng {
	extern StrGlobaliTomb4 &GlobTomb4;
	extern StrGlobAddress &AdrGlobali;
	extern StrMyGlob &MyGlobPrivate;
	extern StrBaseCustomize &BaseCustomize;
	extern StrGlobMisc &BaseGlobMisc;
	extern char (&Dir_Trle)[256];
	extern int &TotAllocata;
	extern bool &TestDebugLog;
	extern DWORD &DefValoreZero;
	extern int &TipoExe;
	extern int &TotCheckMemory;
	extern StrBaseVarAll &BaseVariableTRNG;
	extern StrPanelloSavegame &BasePanello;
	extern StrBaseScriptImages &BaseScriptImages;
	extern StrBaseTriggerGroups &BaseTriggerGroups;
	extern StrBaseCustomize &BaseCustomizeDefault;
	extern BaseScriptOrganizer &BaseOrganizer;
	extern StrBaseGlobalTriggers &BaseGlobalTriggers;
	extern StrBaseScriptEnvCondition &BaseEnvConditions;
	extern StrBaseEffects &BaseEffects;
	extern StrScriptLevel &ScriptLevelNow;
	extern StrBaseDiagnostica &BaseDiagnostica;
	extern StrDatiVariabili &DatiVariabili;
	extern StrDatiVariabili &DatiVarLara;
	extern BaseAnimScript &BaseAnimations;
	extern StrRecording &BaseDemo;
	extern StrDemo &DemoTitle;
	extern StrDemo &DemoLevel;
	extern StrBaseCutscene &BaseCutscene;
	extern StrBaseSwapAnim &BaseSwapAnim;
	extern StrBaseMemSwapAnim &BaseMemSwapAnim;
	extern StrBaseSpeechActor &BaseSpeechActor;
	extern StrPluginNames (&VetPluginNgle)[MAX_PLUGINS_NGLE];
	extern StrTablePluginIdFloor &PluginFloorTable;
	extern StrTableScriptPlugin &PluginScriptTable;
	extern int (&VetMeshSwapSlot)[78];
	extern int (&VetStandardSwapMesh)[107];
	extern int (&VetSlotMeshMoveables)[122];
	extern TYPE_tombInviaLog &tombInviaLog;
	extern BYTE &FlagMicroCaratteri;
	extern char (&MexNewWindowTitle)[256];
	extern char (&BufferLog)[8192];
	extern StrFloatPatch (&VetFarWorld)[5];
	extern int &NuovoFlagCapelli;
	extern POINT (&VetSizeInner)[6];
	extern short (&VetOriginali)[6];
	extern short (&VetDetectorBig)[6];
	extern short (&VetDetectorLittle)[6];
	extern TYPE_IsComandoPremuto &IsComandoPremuto;
	extern TYPE_StopAllSounds &StopAllSounds;
	extern HDC &GlobHdcTomb;
	extern DWORD &ContatoreFiato;
	extern int &ReturnValue;

	void ImpostaEnemyDamage(void);
	bool Inizializza(void);
	void LinkGlobTomb4Structures(void);
	bool IsAttivoDebugger(void);
	char *TrovaVersioneFile(const char *NomeFile, char *pBufProductVersion);
	void CalcolaVersione(StrVersionHeader *pBaseVer);
	void InizializzaTomb4(void);
	bool InviaLog(const char *pMessaggio);
	void GestioneDgxErrori(const char *pMex);
	bool ScopreModoFullScreen(void);
	void InitStringOffsets(void);
	void AnalisiWideScreen(void);
	BYTE *CaricaTomb4Mem(void);
	void Controllo1FileMancanti(void);
	bool EsisteFile(const char *NomeFile);
	void InitPrintTextColors(void);
	void InitBarDefault(void);
	void CustDefToCustNow(void);
	bool LeggeNGScriptDat(char NomeScriptDat[]);
	void InitDgxErrors(void);
	void ImpostaCostantiNascoste(void);
	void InitRemapItemGroup(void);
	void VerifyImagesPix(void);
	StrListaFiles *TrovaFiles(const char DirSource[], const char Maschera[], int *pTotFiles);
	void LeggeMieSettingRegister(void);
	void VerificaAttivazioneSoftFullScreen(void);
	void VerificaAttivazioneNoWaitingRefresh(void);
	void RestyleWindow(void);
	void InitFmvLog(const char *pMex, bool TestCancellaLog);
	void CaricaNGStringTemp(void);
	void MessageBoxTomb(const char *pMessaggio, const char *pTitolo);
	bool ExtractNGHeader(char *pNomeFile, StrExtractNG* pExtractNG);
	long QuantoLungo(FILE *tempfile);
	bool ParseNgField(WORD *pNgArray, DWORD CurrentIndex, StrParseNGField* pParseNGField);
	char *GetStringaNG(int Indice);
	void ModificaWorldFarView(WORD NumBlocchi, bool TestHardware);
	void CreaSottoCartelle(char *pNomeFile);
	bool EsisteDirectory(char *NomeDir);
	bool CreaDirectory(char *NomeDir);
	char * GetString(int IndiceStringa);
	void LeggiNG_ScriptForLevel(void);
	void SalvaTagFmv(BYTE ValoreFmv);
	void LiberaCutsceneCamera(void);
	void InizializzaAdaptiveFarView(void);
	void LiberaImmagine(StrRecordImage *pRecord);
	void InitScreenShot(void);
	void LiberaAllFonts(void);
	void SetItemDetector(int TipoDetector);
	void RipristinaTurbo(void);
	bool SetPriority(int Livello);
	bool Livello2Priority(int IndicePriority, DWORD *pClasse, DWORD *pThread);
	void RipristinaIndiciSlot(void);
	void RipristinaWorldFarView(void);
	void InizializzaBaseFog(void);
	void RipristinaLevelSettings(void);
	void RestoreHardwareFogSempre(void);
	void RipristinaDefaultPrintString(void);
	void RipristinaDamageSettings(void);
	void CalcolaQuotaTickPerDamage(StrDamage *pRec);
	void RipristinaEnemy(void);
	void ImpostaDefaultWindowsFont(short IDWindowsFont);
	int Float2Int(float x);
	float RapportoFloatSchermo(int SizeSchermo, float SchermoRef, float Cord);
	int Casuale(int Massimo);
	void AnnullaIndiceSlot(WORD IndiceSlot);
	int GetPluginIndex(int PluginId, int FromPlug);
	bool AggiungiImmaginePreload(int NImage);
	void ImpostaStandBy1(int Indice);
	void EseguiCustomize(int CustTipo, short *VArg, int TotArg);
	DWORD TrovaColoreRGB(int IdColor);
	void InitAmmoCust(short SlotArma, short VetArg[], bool TestTitle);
	void InitWeaponCust(short SlotArma, short VetArg[], bool TestTitle);
	void ScansioneTextFormat(StrPrintString *pText, WORD VetScript[]);
	COLORREF GetColoreId(short IdColorRgb, COLORREF ColoreDef, bool TestInverti, char *pMexComando);
	const char * ScompattaNomeFont(const char NomeFont[], int *pCharSet);
	void MiaCombineItems(bool TestSepara);
	WORD GestionePickups(WORD Slot, int Operazione, char Valore);
	void AggiungiCombinabile(WORD ItemIndex);
	void RicreaNomiWav(int TipoExtWav);
	void ModificaFogEnd(void);
	void SetFogEnd(void);
	void ModificaFogStart(void);
	void ModificaHardwareFog(void);
	void ModificaFogBulbDistance(void);
	void InizioCiclo(void);
	void AggiornaCutsceneCamera(StrCutsceneCamera *pCut);
	DWORD GetCutsceneFrame(void);
	void CalcolaIncremento(WORD Orientamento, int *pIncX, int *pIncZ, int Distanza);
	int ProporzioneDistanza(int Incremento, int Distanza);
	void GestioneComandiSpeech(void);
	void ShowMsgDebug(const TCHAR *szFormat, ...);
	void ImpostaMeshHead(StrPlaySpeech *pPlay, int MeshIndex);
	WORD GetMeshSpeech(StrPlaySpeech *pPlay, int MeshIndex);
	void EliminaStringaSpeech(StrPlaySpeech *pPlay);
	void GestioneCompletedProgActions(int ActionType, int ActionIndex);
	void FormattaLogCutscene(const char *pMexTipo, DWORD Frame, const char *pMexBase, int Arg1, int Arg2);
	void StampaLogCutscene(char *pMex);
	int EsecuzioneFlipeffect(WORD PluginId, int NumeroFlip, WORD Timer, WORD Flags);
	void ImpostaPosizioneSuono(StrCanaleBass *pCanale, DWORD Posizione);
	int EseguiTriggerGroup(short IdTriggerGroup);
	void SubTabLogScript(void);
	void AnalisiCameraTarget(StrTriggerGroup *pGroup);
	int CreaNuovaAzioneProgressiva(void);
	void PrintLogCommand(StrScriptTrigger *pTrigger, int Index);
	DWORD LeggiDirectInput(void);
	void ScansioneInput(void);
	void GestioneDemo(bool TestFakeUpdateInput);
	void SalvaDatiInizioDemo(StrRecording *pRec);
	void GestioneDemoOrganizer(StrDemo *pDemo, int IndexFrame);
	void TerminaAllSpeech(void);
	void SalvaDemo(int NumeroDemo);
	void AggiornaListaDemo(void);
	void TrovaDemoNumeri(void);
	bool CaricaDemo(int NumeroDemo);
	char *FormattaFrames2Time(DWORD TotFrames, DWORD FrameIndex);
	int ConvertiTombRoomIndex2NgleIndex(int RoomIndex);
	DWORD ReadCurrentGameCommands(void);
	int GestioneDemoInProgress(WORD FlagGestioneDemo, StrDemo *pDemo);
	void StampaStringaDef(char *pTesto, int NumeroCicli);
	void AggiornaPosStringa(StrProgressiveAction *pAzione);
	void ConvertiCord1024(int *pCordX, int *pCordY);
	int ContaRigheInTesto(char *pTesto);
	int AdattaCordX(int CordX);
	int AdattaCordY(int CordY);
	void AggiornaPositioneLara(DWORD CordX, int CordY, DWORD CordZ, short NewRoom, bool TestVariaAltezza);
	DWORD DecodeGameCommand(DWORD CommandData);
	char *FormattaGameCommands(DWORD Flags);
	bool TastoVKPremuto(int VirtualKey);
	int ConvertiTombItemIndex2NgleIndex(int TombIndex);
	int EseguiScriptTrigger(StrScriptTrigger *pTrigger, int Index);
	int GetNgleIndice(int TombIndice);
	int EseguiCondizione(WORD PluginId, WORD Condizione, WORD Indice, WORD ExtraButtons, bool *pTestRestore, bool *pTestSalta, int *pRepeatType, WORD Flags);
	bool IsValidConditionForDummy(int Condizione, int MainArgument, bool TestFirst);
	int PerformTRNGCondition(WORD ConditionNumber, WORD MainArgument, WORD ExtraButtons, bool *pTestRestore, bool *pTestSkipObject, int *pRepeatType, WORD Flags);
	int EsecuzioneActionTrigger(WORD PluginID, WORD AzioneTimer, int ItemIndex, WORD Flags);
	int PerformTRNGAction(WORD AzioneTimer, int ItemIndex, WORD Flags);
	WORD GetNextTriggerFlag(StrTriggerGroup *pGroup, int IndexNow);
	void ImpostaComandoSpeech(StrPlaySpeech *pPlay);
	void PreparaSequenzaSpeech(StrPlaySpeech *pPlay, int Inizio, int Fine, int FrameSet, int TotSyll);
	void ControllaAnchoredBoat(int IndiceVeicolo);
	bool AllocaHdcTomb(StrShowImage *pBase, bool TestHdcTemp, bool TestWriteHdc);
	void LiberaHdcTomb(StrShowImage *pBase, bool TestMantieniTemp);
	void RilasciaTomb4Hdc(void);
	HDC GetHdcTomb(void);
	bool AllocaImmagine(int NImage, StrRecordImage *pRecord, int ForceSizeX, int ForceSizeY);
	bool AnalisiPatchPushAway(void);
	void AvviaDiario(void);
	StrBaseDiario* GetDiarioConID(WORD Id);
	void LiberaWindowsFont(StrWindowsFont *pFont);
	DWORD TrovaPosizioneSuono(StrCanaleBass *pCanale);
	void SospendiThreadNotifica(void);
	char *FormattaTimer(int Valore);
	void SalvaShotTomb4(const char *NomeFile, bool TestFullScreen);
	void AttendiFineEscape(void);
	void RiprendiThreadNotifica(void);
	void ResetScanActions(void);
	void ResetScanFlipEffects(void);
	void GestioneRaisePushables(void);
	bool IsSopraPedana(StrItemTr4 *pOggetto, int *pCordY);
	int TrovaCordYRais(StrItemTr4 *pRaise, int PushY);
	void GestioneItemsSuElevatore(void);
	void AggiornaPosizioneItem(short ItemIndex, DWORD CordX, int CordY, DWORD CordZ, int ExtraY);
	bool IsDoor(WORD Slot);
	void InizializzaCondizioniGlobali(void);
	void InizializzaCollisioniLara(void);
	void ImpostaStatusRoom(void);
	bool IsLaraHolding(int TipoHold);
	void EsecuzioniFlipEffects(void);
	void ElaboraScanAzioni(void);
	void EsecuzioneAzioniProgressive(void);
	void EsegueAzioneProgressiva(int IndiceAzione);
	int FineCiclo(void);
	void GestioneCreatedItems(void);
	bool GestioneGlobaleOk(StrGlobalTrigger *pRec, bool TestEsegui);
	void EseguiTriggerGlobale(StrGlobalTrigger *pRec, bool TestCondizione);
	void TaraMieiOggetti(void);
	void AggiornaRollBoats(void);
	bool IsKayakSpiaggiata(StrItemTr4 *pItem);
	void NuovaDirezioneDeriva(StrItemTr4 *pItem, StrRollBoat *pRoll);
	bool EsisteAcqua(DWORD CordX, int CordY, DWORD CordZ, short Room);
	void TrovaItemUsedByLara(void);
	void ImpostaTempoUltimoComando(void);
	void InizializzaStandBy(StrBaseStandBy *pStand);
	bool TestLaraMurata(int Distanza);
	void TerminaStandBy(StrBaseStandBy *pStand);
	void ControllaMorteCreature(void);
	void EseguiAnimNemico(StrItemTr4 *pOggetto, WORD IndiceAnim, short NextStateId);
	bool GestioneDemoTitle(StrDemo *pDemo);
	bool ScegliDemoTitle(StrDemo *pDemo);
	void ControllaTriggerGlobali(void);
	bool DistanzaDaLaraEntro(StrMovePosition *pPos, DWORD Distanza, bool TestIgnoraY);
	bool IsItemVicinoLara(StrMovePosition *pPos, int Distanza, bool TestIgnoraY);
	int GetIndiceItem(DWORD OffsetItem);
	bool IsEventoNow(short GT_Evento, short Parameter, bool TestRimuovi);
	void ControllaCheatsNG(void);
	BYTE GetLetteraPremuta(void);
	void CreaLuceFlareForLara(void);
	void GestioneCollisioneStatic(void);
	void EseguiAnimazione(WORD NumeroAnimazione, int IndiceSlot, bool TestUsaNextId);
	void GestioneAdaptiveFarView(void);
	void ControllaOrganizer(void);
	void GestioneDamage(bool TestDamage);
	void MostraStringaDamage(StrDamage *pRec);
	void AggiornaAdrStringa(StrProgressiveAction *pAzione);
	void ControllaMorteLara(StrItemTr4* pLara);
	void EliminaStringaDamage(short Indice);
	void GestioneJiga(void);
	void GestioneAnimazioni(void);
	bool EseguireAnimazioneScript(StrAnimScript *pAnimazione, StrItemTr4 *pOggetto, bool TestLara, short ItemIndex);
	bool ControllaENVFlags(WORD EnvFlags);
	WORD GetAlignedOrient(short Orient, bool TestForceHortogonal, int *pGap);
	int AbsDiffO(short First, short Second);
	bool TestEnvCondition(WORD EnvCondizione, WORD FlagCondition, short DistanzaEnv, WORD Extra);
	void BackupLara(StrBackupLara *pBack, StrItemTr4 *pOggetto);
	void RestoreLara(StrBackupLara *pBack, StrItemTr4 *pOggetto);
	void SospendiHardCoded(int NAnimazione, int FrameToWait);
	void AggiornaMirrorAnimating(void);
	void VerificaAttivazioneDetector(void);
	void CalcolaDetector(void);
	WORD CalcolaDirezioneDetector(int ItemIndex);
	WORD TrovaOrientamentoOggetti(DWORD CordX, DWORD CordZ, StrItemTr4 *pLara);
	void ShowDetector(void);
	void CambiaMascheraSaveGame(void);
	void RipristinaMascheraSaveGame(void);
	void RiempiDatiVariabili(void);
	void FormattaHeaderSavegame(WORD **pVettoreWords, int *pNumeroWords, bool TestCompleto, bool TestSoloLara);
	void CopiaInHeader(WORD NGTag, DWORD TotItem, DWORD SizeSingleItem, void *pDato, WORD **p2VetExtra, int *pNWords);
	void TrovaTimerOggetti(void);
	void PreparaSavegameInfos(void);
	void TrovaStaticsAlterati(void);
	int TrovaIndiceMainRoom(int IndiceRoom);
	short *CreaDatiDiari(WORD *pTotShorts);
	BYTE *PreparaDatiKayak(void);
	StrDatiVariabili * EstraiDatiVariabili(bool TestSoloLara);
}

void LoadTombNextGenerationInject_TombNextGeneration(bool replace);
