#pragma once
#include <stdio.h>
#include "structures.h"
#include "MyStructures.h"
#include "DefTomb4Funct.h"

namespace trng {
	extern StrGlobaliTomb4 &GlobTomb4;
	extern StrGlobAddress &AdrGlobali;
	extern StrMyGlob &MyGlobPrivate;
	extern StrBaseCustomize &BaseCustomize;
	extern StrGlobMisc &BaseGlobMisc;
	extern char (&Dir_Trle)[256];
	extern int &TotAllocata;
	extern bool &TestDebugLog;
	extern DWORD &DefValoreZero;
	extern int &TipoExe;
	extern int &TotCheckMemory;
	extern StrBaseVarAll &BaseVariableTRNG;
	extern StrPanelloSavegame &BasePanello;
	extern StrBaseScriptImages &BaseScriptImages;
	extern StrBaseTriggerGroups &BaseTriggerGroups;
	extern StrBaseCustomize &BaseCustomizeDefault;
	extern BaseScriptOrganizer &BaseOrganizer;
	extern StrBaseGlobalTriggers &BaseGlobalTriggers;
	extern StrBaseScriptEnvCondition &BaseEnvConditions;
	extern StrBaseEffects &BaseEffects;
	extern StrScriptLevel &ScriptLevelNow;
	extern StrBaseDiagnostica &BaseDiagnostica;
	extern StrDatiVariabili &DatiVariabili;
	extern StrDatiVariabili &DatiVarLara;
	extern BaseAnimScript &BaseAnimations;
	extern StrRecording &BaseDemo;
	extern StrDemo &DemoTitle;
	extern StrDemo &DemoLevel;
	extern StrBaseCutscene &BaseCutscene;
	extern StrBaseSwapAnim &BaseSwapAnim;
	extern StrBaseMemSwapAnim &BaseMemSwapAnim;
	extern StrBaseSpeechActor &BaseSpeechActor;
	extern StrPluginNames (&VetPluginNgle)[MAX_PLUGINS_NGLE];
	extern StrTablePluginIdFloor &PluginFloorTable;
	extern StrTableScriptPlugin &PluginScriptTable;
	extern int (&VetMeshSwapSlot)[78];
	extern int (&VetStandardSwapMesh)[107];
	extern int (&VetSlotMeshMoveables)[122];
	extern TYPE_tombInviaLog &tombInviaLog;
	extern BYTE &FlagMicroCaratteri;
	extern char (&MexNewWindowTitle)[256];
	extern char (&BufferLog)[8192];
	extern StrFloatPatch (&VetFarWorld)[5];
	extern int &NuovoFlagCapelli;
	extern POINT (&VetSizeInner)[6];
	extern short (&VetOriginali)[6];
	extern short (&VetDetectorBig)[6];
	extern short (&VetDetectorLittle)[6];
	extern TYPE_IsComandoPremuto &IsComandoPremuto;
	extern TYPE_StopAllSounds &StopAllSounds;

	void ImpostaEnemyDamage(void);
	bool Inizializza(void);
	void LinkGlobTomb4Structures(void);
	bool IsAttivoDebugger(void);
	char *TrovaVersioneFile(const char *NomeFile, char *pBufProductVersion);
	void CalcolaVersione(StrVersionHeader *pBaseVer);
	void InizializzaTomb4(void);
	bool InviaLog(const char *pMessaggio);
	void GestioneDgxErrori(const char *pMex);
	bool ScopreModoFullScreen(void);
	void InitStringOffsets(void);
	void AnalisiWideScreen(void);
	BYTE *CaricaTomb4Mem(void);
	void Controllo1FileMancanti(void);
	bool EsisteFile(const char *NomeFile);
	void InitPrintTextColors(void);
	void InitBarDefault(void);
	void CustDefToCustNow(void);
	bool LeggeNGScriptDat(char NomeScriptDat[]);
	void InitDgxErrors(void);
	void ImpostaCostantiNascoste(void);
	void InitRemapItemGroup(void);
	void VerifyImagesPix(void);
	StrListaFiles *TrovaFiles(const char DirSource[], const char Maschera[], int *pTotFiles);
	void LeggeMieSettingRegister(void);
	void VerificaAttivazioneSoftFullScreen(void);
	void VerificaAttivazioneNoWaitingRefresh(void);
	void RestyleWindow(void);
	void InitFmvLog(const char *pMex, bool TestCancellaLog);
	void CaricaNGStringTemp(void);
	void MessageBoxTomb(const char *pMessaggio, const char *pTitolo);
	bool ExtractNGHeader(char *pNomeFile, StrExtractNG* pExtractNG);
	long QuantoLungo(FILE *tempfile);
	bool ParseNgField(WORD *pNgArray, DWORD CurrentIndex, StrParseNGField* pParseNGField);
	char *GetStringaNG(int Indice);
	void ModificaWorldFarView(WORD NumBlocchi, bool TestHardware);
	void CreaSottoCartelle(char *pNomeFile);
	bool EsisteDirectory(char *NomeDir);
	bool CreaDirectory(char *NomeDir);
	char * GetString(int IndiceStringa);
	void LeggiNG_ScriptForLevel(void);
	void SalvaTagFmv(BYTE ValoreFmv);
	void LiberaCutsceneCamera(void);
	void InizializzaAdaptiveFarView(void);
	void LiberaImmagine(StrRecordImage *pRecord);
	void InitScreenShot(void);
	void LiberaAllFonts(void);
	void SetItemDetector(int TipoDetector);
	void RipristinaTurbo(void);
	bool SetPriority(int Livello);
	bool Livello2Priority(int IndicePriority, DWORD *pClasse, DWORD *pThread);
	void RipristinaIndiciSlot(void);
	void RipristinaWorldFarView(void);
	void InizializzaBaseFog(void);
	void RipristinaLevelSettings(void);
	void RestoreHardwareFogSempre(void);
	void RipristinaDefaultPrintString(void);
	void RipristinaDamageSettings(void);
	void CalcolaQuotaTickPerDamage(StrDamage *pRec);
	void RipristinaEnemy(void);
	void ImpostaDefaultWindowsFont(short IDWindowsFont);
	int Float2Int(float x);
	float RapportoFloatSchermo(int SizeSchermo, float SchermoRef, float Cord);
	int Casuale(int Massimo);
	void AnnullaIndiceSlot(WORD IndiceSlot);
	int GetPluginIndex(int PluginId, int FromPlug);
	bool AggiungiImmaginePreload(int NImage);
	void ImpostaStandBy1(int Indice);
	void EseguiCustomize(int CustTipo, short *VArg, int TotArg);
	DWORD TrovaColoreRGB(int IdColor);
	void InitAmmoCust(short SlotArma, short VetArg[], bool TestTitle);
	void InitWeaponCust(short SlotArma, short VetArg[], bool TestTitle);
	void ScansioneTextFormat(StrPrintString *pText, WORD VetScript[]);
	COLORREF GetColoreId(short IdColorRgb, COLORREF ColoreDef, bool TestInverti, char *pMexComando);
	const char * ScompattaNomeFont(const char NomeFont[], int *pCharSet);
	void MiaCombineItems(bool TestSepara);
	WORD GestionePickups(WORD Slot, int Operazione, char Valore);
	void AggiungiCombinabile(WORD ItemIndex);
	void RicreaNomiWav(int TipoExtWav);
	void ModificaFogEnd(void);
	void SetFogEnd(void);
	void ModificaFogStart(void);
	void ModificaHardwareFog(void);
	void ModificaFogBulbDistance(void);
	void InizioCiclo(void);
	void AggiornaCutsceneCamera(StrCutsceneCamera *pCut);
	DWORD GetCutsceneFrame(void);
	void CalcolaIncremento(WORD Orientamento, int *pIncX, int *pIncZ, int Distanza);
	int ProporzioneDistanza(int Incremento, int Distanza);
	void GestioneComandiSpeech(void);
	void ShowMsgDebug(const TCHAR *szFormat, ...);
	void ImpostaMeshHead(StrPlaySpeech *pPlay, int MeshIndex);
	WORD GetMeshSpeech(StrPlaySpeech *pPlay, int MeshIndex);
	void EliminaStringaSpeech(StrPlaySpeech *pPlay);
	void GestioneCompletedProgActions(int ActionType, int ActionIndex);
	void FormattaLogCutscene(const char *pMexTipo, DWORD Frame, const char *pMexBase, int Arg1, int Arg2);
	void StampaLogCutscene(char *pMex);
	int EsecuzioneFlipeffect(WORD PluginId, int NumeroFlip, WORD Timer, WORD Flags);
	void ImpostaPosizioneSuono(StrCanaleBass *pCanale, DWORD Posizione);
	int EseguiTriggerGroup(short IdTriggerGroup);
	void SubTabLogScript(void);
	void AnalisiCameraTarget(StrTriggerGroup *pGroup);
	int CreaNuovaAzioneProgressiva(void);
	void PrintLogCommand(StrScriptTrigger *pTrigger, int Index);
	DWORD LeggiDirectInput(void);
	void ScansioneInput(void);
	void GestioneDemo(bool TestFakeUpdateInput);
	void SalvaDatiInizioDemo(StrRecording *pRec);
	void GestioneDemoOrganizer(StrDemo *pDemo, int IndexFrame);
	void TerminaAllSpeech(void);
	void SalvaDemo(int NumeroDemo);
	void AggiornaListaDemo(void);
	void TrovaDemoNumeri(void);
	bool CaricaDemo(int NumeroDemo);
	char *FormattaFrames2Time(DWORD TotFrames, DWORD FrameIndex);
	int ConvertiTombRoomIndex2NgleIndex(int RoomIndex);
	DWORD ReadCurrentGameCommands(void);
	int GestioneDemoInProgress(WORD FlagGestioneDemo, StrDemo *pDemo);
	void StampaStringaDef(char *pTesto, int NumeroCicli);
	void AggiornaPosStringa(StrProgressiveAction *pAzione);
	void ConvertiCord1024(int *pCordX, int *pCordY);
	int ContaRigheInTesto(char *pTesto);
	int AdattaCordX(int CordX);
	int AdattaCordY(int CordY);
	void AggiornaPositioneLara(DWORD CordX, int CordY, DWORD CordZ, short NewRoom, bool TestVariaAltezza);
	DWORD DecodeGameCommand(DWORD CommandData);
	char *FormattaGameCommands(DWORD Flags);
	bool TastoVKPremuto(int VirtualKey);
	int ConvertiTombItemIndex2NgleIndex(int TombIndex);
	int EseguiScriptTrigger(StrScriptTrigger *pTrigger, int Index);
	int GetNgleIndice(int TombIndice);
	int EseguiCondizione(WORD PluginId, WORD Condizione, WORD Indice, WORD ExtraButtons, bool *pTestRestore, bool *pTestSalta, int *pRepeatType, WORD Flags);
	bool IsValidConditionForDummy(int Condizione, int MainArgument, bool TestFirst);
	int PerformTRNGCondition(WORD ConditionNumber, WORD MainArgument, WORD ExtraButtons, bool *pTestRestore, bool *pTestSkipObject, int *pRepeatType, WORD Flags);
	int EsecuzioneActionTrigger(WORD PluginID, WORD AzioneTimer, int ItemIndex, WORD Flags);
	int PerformTRNGAction(WORD AzioneTimer, int ItemIndex, WORD Flags);
	WORD GetNextTriggerFlag(StrTriggerGroup *pGroup, int IndexNow);
	void ImpostaComandoSpeech(StrPlaySpeech *pPlay);
	void PreparaSequenzaSpeech(StrPlaySpeech *pPlay, int Inizio, int Fine, int FrameSet, int TotSyll);
	void ControllaAnchoredBoat(int IndiceVeicolo);
	bool AnalisiPatchPushAway(void);
	void AvviaDiario(void);
	void ResetScanActions(void);
	void ResetScanFlipEffects(void);
	void GestioneRaisePushables(void);
	void GestioneItemsSuElevatore(void);
	void InizializzaCondizioniGlobali(void);
	void InizializzaCollisioniLara(void);
	void ImpostaStatusRoom(void);
}

void LoadTombNextGenerationInject_TombNextGeneration(bool replace);
