#pragma once
#define DIRECT3D_VERSION 0x0600
#include <d3d.h>
#define DIRECTINPUT_VERSION 0x0500
#include <dinput.h>
#include <mmreg.h>
#define DIRECTSOUND_VERSION 0x0500
#include <dsound.h>

namespace tomb4
{
	typedef unsigned char uchar;
	typedef unsigned short ushort;
	typedef unsigned long ulong;

	inline constexpr long W2V_SHIFT = 14;

	enum mood_type
	{
		BORED_MOOD,
		ATTACK_MOOD,
		ESCAPE_MOOD,
		STALK_MOOD
	};

	enum zone_type
	{
		SKELLY_ZONE,
		BASIC_ZONE,
		CROC_ZONE,
		HUMAN_ZONE,
		FLYER_ZONE
	};

	enum sfx_options
	{
		SFX_DEFAULT = 0,
		SFX_WATER = 1,
		SFX_ALWAYS = 2,
		SFX_SETPITCH = 4
	};

	enum sound_effect_names
	{
		SFX_LARA_FEET,
		SFX_LARA_CLIMB2,
		SFX_LARA_NO,
		SFX_LARA_SLIPPING,
		SFX_LARA_LAND,
		SFX_LARA_CLIMB1,
		SFX_LARA_DRAW,
		SFX_LARA_HOLSTER,
		SFX_LARA_FIRE,
		SFX_LARA_RELOAD,
		SFX_LARA_RICOCHET,
		SFX_PUSH_BLOCK_END,
		SFX_METAL_SCRAPE_LOOP1,
		SFX_SMALL_SCARAB_FEET,
		SFX_BIG_SCARAB_ATTACK,
		SFX_BIG_SCARAB_DEATH,
		SFX_BIG_SCARAB_FLYING,
		SFX_LARA_WET_FEET,
		SFX_LARA_WADE,
		SFX_RUMBLE_LOOP,
		SFX_METAL_SCRAPE_LOOP,
		SFX_CRICKET_LOOP,
		SFX_WOOD_BRIDGE_FALL,
		SFX_STARGATE_SWIRL,
		SFX_LARA_KNEES_SHUFFLE,
		SFX_PUSH_SPX_SWITCH,
		SFX_LARA_CLIMB3,
		SFX_UNUSED,
		SFX_LARA_SHIMMY2,
		SFX_LARA_JUMP,
		SFX_LARA_FALL,
		SFX_LARA_INJURY,
		SFX_LARA_ROLL,
		SFX_LARA_SPLASH,
		SFX_LARA_GETOUT,
		SFX_LARA_SWIM,
		SFX_LARA_BREATH,
		SFX_LARA_BUBBLES,
		SFX_SPINNING_PUZZLE,
		SFX_LARA_KEY,
		SFX_COG_RESAW_LIBRARY,
		SFX_LARA_GENERAL_DEATH,
		SFX_LARA_KNEES_DEATH,
		SFX_LARA_UZI_FIRE,
		SFX_LARA_UZI_STOP,
		SFX_LARA_SHOTGUN,
		SFX_LARA_BLOCK_PUSH1,
		SFX_LARA_BLOCK_PUSH2,
		SFX_SARLID_PALACES,
		SFX_LARA_SHOTGUN_SHELL,
		SFX_UNDERWATER_DOOR,
		SFX_LARA_BLKPULL,
		SFX_LARA_FLOATING,
		SFX_LARA_FALLDEATH,
		SFX_LARA_GRABHAND,
		SFX_LARA_GRABBODY,
		SFX_LARA_GRABFEET,
		SFX_RATCHET_3SHOT,
		SFX_RATCHET_1SHOT,
		SFX_WATER_LOOP_NOTINUSE,
		SFX_UNDERWATER,
		SFX_UNDERWATER_SWITCH,
		SFX_LARA_PICKUP,
		SFX_PUSHABLE_SOUND,
		SFX_DOOR_GENERAL,
		SFX_HELICOPTER_LOOP,
		SFX_ROCK_FALL_CRUMBLE,
		SFX_ROCK_FALL_LAND,
		SFX_PENDULUM_BLADES,
		SFX_STALEGTITE,
		SFX_LARA_THUD,
		SFX_GENERIC_SWOOSH,
		SFX_GENERIC_HEAVY_THUD,
		SFX_CROC_FEET,
		SFX_SWINGING_FLAMES,
		SFX_STONE_SCRAPE,
		SFX_BLAST_CIRCLE,
		SFX_BAZOOKA_FIRE,
		SFX_MP5_FIRE,
		SFX_WATERFALL_LOOP,
		SFX_CROC_ATTACK,
		SFX_CROC_DEATH,
		SFX_PORTCULLIS_UP,
		SFX_PORTCULLIS_DOWN,
		SFX_DOUBLE_DOOR_BANG,
		SFX_DOUBLE_DOOR_CREAK,
		SFX_PETES_PYRA_STONE,
		SFX_PETES_PYRA_PNEU,
		SFX_AHMET_DIE,
		SFX_AHMET_ATTACK,
		SFX_AMHET_HANDS,
		SFX_AHMET_FEET,
		SFX_AHMET_SWIPE,
		SFX_AHMET_WAIT,
		SFX_GUIDE_JUMP,
		SFX_GENERAL_FOOTSTEPS1,
		SFX_GUIDE_LAND_USENOT,
		SFX_POUR,
		SFX_SCALE1,
		SFX_SCALE2,
		SFX_BEETLARA_WINDUP,
		SFX_BEETLE_CLK_WHIRR,
		SFX_BEETLE_CLK_EXP,
		SFX_MINE_EXP_OVERLAY,
		SFX_MP5_STOP,
		SFX_EXPLOSION1,
		SFX_EXPLOSION2,
		SFX_EARTHQUAKE_LOOP,
		SFX_MENU_ROTATE,
		SFX_MENU_SELECT,
		SFX_MENU_EMPTY,
		SFX_MENU_CHOOSE,
		SFX_TICK_TOCK,
		SFX_MENU_EMPTY1,
		SFX_MENU_COMBINE,
		SFX_MENU_EMPTY2,
		SFX_MENU_MEDI,
		SFX_LARA_CLIMB_WALLS_NOISE,
		SFX_WATER_LOOP,
		SFX_VONCROY_JUMP,
		SFX_LOCUSTS_LOOP,
		SFX_DESERT_EAGLE_FIRE,
		SFX_BOULDER_FALL,
		SFX_LARA_MINI_LOAD,
		SFX_LARA_MINI_LOCK,
		SFX_LARA_MINI_FIRE,
		SFX_GATE_OPENING,
		SFX_LARA_ELECTRIC_LOOP,
		SFX_LARA_ELECTRIC_CRACKLES,
		SFX_BLOOD_LOOP,
		SFX_BIKE_START,
		SFX_BIKE_IDLE,
		SFX_BIKE_ACCELERATE,
		SFX_BIKE_MOVING,
		SFX_BIKE_SIDE_IMPACT,
		SFX_BIKE_FRONT_IMPACT,
		SFX_SOFT_WIND_LOOP,
		SFX_BIKE_LAND,
		SFX_CROCGOD_ROAR,
		SFX_CROCGOD_WINGS,
		SFX_CROCGOD_LAND,
		SFX_CROCGOD_FIRE_ROAR,
		SFX_BIKE_STOP,
		SFX_GENERIC_BODY_SLAM,
		SFX_MP5_OVERLAY,
		SFX_LARA_SPIKE_DEATH,
		SFX_LARA_DEATH3,
		SFX_ROLLING_BALL,
		SFX_BLK_PLAT_RAISE_LOW,
		SFX_RUMBLE_NEXTDOOR,
		SFX_LOOP_FOR_SMALL_FIRES,
		SFX_CHAINS_LIBRARY,
		SFX_JEEP_START,
		SFX_JEEP_IDLE,
		SFX_JEEP_ACCELERATE,
		SFX_JEEP_MOVE,
		SFX_JEEP_STOP,
		SFX_BATS_1,
		SFX_ROLLING_DOOR,
		SFX_LAUNCHER_1,
		SFX_LAUNCHER_2,
		SFX_TRAPDOOR_OPEN,
		SFX_TRAPDOOR_CLOSE,
		SFX_EMPTY1,
		SFX_BABOON_STAND_WAIT,
		SFX_BABOON_ATTACK_LOW,
		SFX_BABOON_ATTACK_JUMP,
		SFX_BABOON_JUMP,
		SFX_BABOON_DEATH,
		SFX_BAT_SQUEAL_FULL,
		SFX_BAT_SQK,
		SFX_BAT_FLAP,
		SFX_SPHINX_NOSE_RASP,
		SFX_SPHINX_WALK,
		SFX_SPHINX_NOISE,
		SFX_DOG_HOWL,
		SFX_DOG_HIT_GOUND,
		SFX_FOUNTAIN_LOOP,
		SFX_DOG_FOOT_1,
		SFX_DOG_JUMP,
		SFX_DOG_BITE,
		SFX_DOG_DEATH,
		SFX_THUNDER_RUMBLE,
		SFX_THUNDER_CRACK,
		SFX_WRAITH_WHISPERS,
		SFX_EMPTY2,
		SFX_EMPTY3,
		SFX_SKEL_FOOTSTEP,
		SFX_SKEL_ATTACK,
		SFX_GENERIC_SWORD_SWOOSH,
		SFX_SKEL_SWORD_CLANG,
		SFX_SKEL_STICK_GROUND,
		SFX_GEN_PULL_SWORD,
		SFX_SKEL_LAND_HEAVY,
		SFX_GUIDE_SCARE,
		SFX_JEEP_DOOR_OPEN,
		SFX_JEEP_DOOR_CLOSE,
		SFX_ELEC_ARCING_LOOP,
		SFX_ELEC_ONE_SHOT,
		SFX_EMPTY4,
		SFX_LIBRARY_COG_LOOP,
		SFX_JEEP_SIDE_IMPACT,
		SFX_JEEP_FRONT_IMPACT,
		SFX_JEEP_LAND,
		SFX_SPINNING_GEM_SLOTS,
		SFX_RUMMBLE,
		SFX_WARTHOG_HEADBUTT,
		SFX_WARTHOG_DEATH,
		SFX_SET_SPIKE_TIMER,
		SFX_WARTHOG_SQUEAL,
		SFX_WARTHOG_FEET,
		SFX_WARTHOG_GRUNT,
		SFX_SAVE_CRYSTAL,
		SFX_HORSE_RICOCHETS,
		SFX_METAL_SHUTTERS_SMASH,
		SFX_GEM_DROP_ON_FLOOR,
		SFX_SCORPION_SCREAM,
		SFX_SCORPION_FEET,
		SFX_SCORPION_CLAWS,
		SFX_SCORPION_TAIL_WHIP,
		SFX_SCORPION_SMALL_FEET,
		SFX_METAL_GATE_OPEN,
		SFX_HORSE_TROTTING,
		SFX_KN_TEMPLAR_WALK,
		SFX_KN_TEMPLAR_GURGLES,
		SFX_KN_SWORD_SCRAPE,
		SFX_KN_TEMPLAR_ATTACK,
		SFX_KN_SWORD_CLANG,
		SFX_KN_SWORD_SWOOSH,
		SFX_MUMMY_ATTACK,
		SFX_MUMMY_WALK,
		SFX_MUMMY_GURGLES,
		SFX_MUMMY_TAKE_HIT,
		SFX_SMALL_FAN,
		SFX_LARGE_FAN,
		SFX_LARA_CROSSBOW,
		SFX_SMALL_CREATURE_FEET,
		SFX_SAS_GADGIE_DIE,
		SFX_WATER_FLUSHES,
		SFX_GUID_ZIPPO,
		SFX_LEAP_SWITCH,
		SFX_OLD_SWITCH,
		SFX_DEMIGODS_FEET,
		SFX_DEMIGODS_BULL_SNORT,
		SFX_DEMIGODS_BULL_HAMMER,
		SFX_DEMIGODS_S_WAVE_RUMB,
		SFX_DEMIGOD_WEAP_SWOOSH,
		SFX_DEMIGOD_FALCON_SQUEAL,
		SFX_DEMIGOD_FALCON_PLAS,
		SFX_DEMIGOD_RISE,
		SFX_DEMI_TUT_PLASMA_SPRAY,
		SFX_DEMI_SIREN_SWAVE,
		SFX_DEMIGODS_TUT_GROWL,
		SFX_JOBY_ELECTRIC_INSERT,
		SFX_BAD_LAND,
		SFX_DOOR_GEN_THUD,
		SFX_BAD_GRUNTS,
		SFX_BAD_DIE,
		SFX_BAD_JUMP,
		SFX_BAD_TROOP_STUN,
		SFX_BAD_SWORDAWAY,
		SFX_BAD_TROOP_UZI,
		SFX_BAD_SWORD_RICO,
		SFX_BAD_TROOP_UZI_END,
		SFX_TROOP_SCROP_CRIES,
		SFX_SAS_TROOP_FEET,
		SFX_GENERIC_NRG_CHARGE,
		SFX_SAS_MG_FIRE,
		SFX_HAMMER_HEAD_WADE,
		SFX_SMALL_SWITCH,
		SFX_EMPTY5,
		SFX_SIREN_WING_FLAP,
		SFX_SIREN_NOIZES,
		SFX_SIREN_ATTACK,
		SFX_SIREN_DEATH,
		SFX_SIREN_GEN_NOISES,
		SFX_SETT_SIREN_PLASMA,
		SFX_HAMMER_HEAD_ATK,
		SFX_SMALL_DOOR_SUBWAY,
		SFX_TRAIN_DOOR_OPEN,
		SFX_TRAIN_DOOR_CLOSE,
		SFX_VONCROY_KNIFE_SWISH,
		SFX_TRAIN_UNLINK_BREAK,
		SFX_OBJ_BOX_HIT,
		SFX_OBJ_BOX_HIT_CHANCE,
		SFX_OBJ_GEM_SMASH,
		SFX_CATBLADES_DRAW,
		SFX_SWIRLY_LONG_MOVE_SFX,
		SFX_FOOTSTEPS_MUD,
		SFX_HORSEMAN_HORSE_NEIGH,
		SFX_FOOTSTEPS_GRAVEL,
		SFX_FOOTSTEPS_SAND_GRASS,
		SFX_FOOTSTEPS_WOOD,
		SFX_FOOTSTEPS_MARBLE,
		SFX_FOOTSTEPS_METAL,
		SFX_GEN_SPHINX_DOORTHD,
		SFX_SETT_PLASMA_1,
		SFX_SETT_BOLT_1,
		SFX_SETT_FEET,
		SFX_SETT_NRG_CHARGE,
		SFX_SETT_NRG_CHARGE2,
		SFX_HORSEMAN_TAKEHIT,
		SFX_HORSEMAN_WALK,
		SFX_HORSEMAN_GRUNT,
		SFX_HORSEMAN_FALL,
		SFX_HORSEMAN_DIE,
		SFX_MAPPER_SWITCH_ON,
		SFX_MAPPER_OPEN,
		SFX_MAPPER_LAZER,
		SFX_MAPPER_MOVE,
		SFX_MAPPER_CLUNK,
		SFX_BLADES_DRAW,
		SFX_BLADES_CLASH_LOUD,
		SFX_BLADES_CLASH_QUIET,
		SFX_HAMMER_TRAP_BANG,
		SFX_DOOR_BIG_STONE,
		SFX_SETT_BIG_ROAR,
		SFX_BABOON_CHATTER,
		SFX_BABOON_ROLL,
		SFX_SWOOSH_SWIRLY_DOUBLE,
		SFX_DOOR_SETTDOOR_SQK,
		SFX_DOOR_SETTDOOR_CLANK,
		SFX_SETT_JUMP_ATTACK,
		SFX_JOBY_BLOCK,
		SFX_SETT_TAKE_HIT,
		SFX_DART_SPITT,
		SFX_LARA_CROWBAR_GEM,
		SFX_CROWBAR_DOOR_OPEN,
		SFX_LARA_LEVER_GEN_SQKS,
		SFX_HORSEMAN_GETUP,
		SFX_EXH_BASKET_OPEN,
		SFX_EXH_MUMCOFF_OPE1,
		SFX_EXH_MUMCOFF_OPE2,
		SFX_EXH_MUM_JOLT,
		SFX_EXH_MUMHEAD_SPIN,
		SFX_EXH_MUMMY_RAHHH,
		SFX_EXH_ROLLER_BLINDS,
		SFX_LARA_LEVER_PART1,
		SFX_LARA_LEVER_PART2,
		SFX_LARA_POLE_CLIMB,
		SFX_LARA_POLE_LOOP,
		SFX_TRAP_SPIKEBALL_SPK,
		SFX_LARA_PULLEY,
		SFX_TEETH_SPIKES,
		SFX_SAND_LOOP,
		SFX_LARA_USE_OBJECT,
		SFX_LIBRARY_COG_SQKS,
		SFX_HIT_ROCK,
		SFX_LARA_NO_FRENCH,
		SFX_LARA_NO_JAPAN,
		SFX_LARA_CROW_WRENCH,
		SFX_LARA_ROPE_CREAK,
		SFX_BOWLANIM,
		SFX_SPHINX_DOOR_WOODCRACK,
		SFX_BEETLE_CLK_WHIRR1,
		SFX_MAPPER_PYRAMID_OPEN,
		SFX_LIGHT_BEAM_JOBY,
		SFX_GUIDE_FIRE_LIGHT,
		SFX_AUTOGUNS,
		SFX_PULLEY_ANDY,
		SFX_STEAM,
		SFX_JOBY_GARAGE_DOOR,
		SFX_JOBY_WIND,
		SFX_SANDHAM_IN_THE_HOUSE,
		SFX_SANDHAM_CONVEYS,
		SFX_CRANKY_GRAPE_CRUSH,
		SFX_BIKE_HIT_OBJECTS,
		SFX_BIKE_HIT_ENEMIES,
		SFX_FLAME_EMITTER,
		SFX_LARA_CLICK_SWITCH,
		NumSamples
	};

	enum matrix_indices
	{
		M00,
		M01,
		M02,
		M03,
		M10,
		M11,
		M12,
		M13,
		M20,
		M21,
		M22,
		M23,
		indices_count
	};

	enum object_types
	{
		LARA,
		PISTOLS_ANIM,
		UZI_ANIM,
		SHOTGUN_ANIM,
		CROSSBOW_ANIM,
		GRENADE_GUN_ANIM,
		SIXSHOOTER_ANIM,
		FLARE_ANIM,
		LARA_SKIN,
		LARA_SKIN_JOINTS,
		LARA_SCREAM,
		LARA_CROSSBOW_LASER,
		LARA_REVOLVER_LASER,
		LARA_HOLSTERS,
		LARA_HOLSTERS_PISTOLS,
		LARA_HOLSTERS_UZIS,
		LARA_HOLSTERS_SIXSHOOTER,
		LARA_SPEECH_HEAD1,
		LARA_SPEECH_HEAD2,
		LARA_SPEECH_HEAD3,
		LARA_SPEECH_HEAD4,
		ACTOR1_SPEECH_HEAD1,
		ACTOR1_SPEECH_HEAD2,
		ACTOR2_SPEECH_HEAD1,
		ACTOR2_SPEECH_HEAD2,
		LARA_WATER_MESH,
		LARA_PETROL_MESH,
		LARA_DIRT_MESH,
		CROWBAR_ANIM,
		TORCH_ANIM,
		HAIR,
		MOTORBIKE,
		JEEP,
		VEHICLE_EXTRA,
		ENEMY_JEEP,
		SKELETON,
		SKELETON_MIP,
		GUIDE,
		GUIDE_MIP,
		VON_CROY,
		VON_CROY_MIP,
		BADDY_1,
		BADDY_1_MIP,
		BADDY_2,
		BADDY_2_MIP,
		SETHA,
		SETHA_MIP,
		MUMMY,
		MUMMY_MIP,
		SPHINX,
		SPHINX_MIP,
		CROCODILE,
		CROCODILE_MIP,
		HORSEMAN,
		HORSEMAN_MIP,
		SCORPION,
		SCORPION_MIP,
		JEAN_YVES,
		JEAN_YVES_MIP,
		TROOPS,
		TROOPS_MIP,
		KNIGHTS_TEMPLAR,
		KNIGHTS_TEMPLAR_MIP,
		MUTANT,
		MUTANT_MIP,
		HORSE,
		HORSE_MIP,
		BABOON_NORMAL,
		BABOON_NORMAL_MIP,
		BABOON_INV,
		BABOON_INV_MIP,
		BABOON_SILENT,
		BABOON_SILENT_MIP,
		WILD_BOAR,
		WILD_BOAR_MIP,
		HARPY,
		HARPY_MIP,
		DEMIGOD1,
		DEMIGOD1_MIP,
		DEMIGOD2,
		DEMIGOD2_MIP,
		DEMIGOD3,
		DEMIGOD3_MIP,
		LITTLE_BEETLE,
		BIG_BEETLE,
		BIG_BEETLE_MIP,
		WRAITH1,
		WRAITH2,
		WRAITH3,
		WRAITH4,
		BAT,
		DOG,
		DOG_MIP,
		HAMMERHEAD,
		HAMMERHEAD_MIP,
		SAS,
		SAS_MIP,
		SAS_DYING,
		SAS_DYING_MIP,
		SAS_CAPTAIN,
		SAS_CAPTAIN_MIP,
		SAS_DRAG_BLOKE,
		AHMET,
		AHMET_MIP,
		LARA_DOUBLE,
		LARA_DOUBLE_MIP,
		SMALL_SCORPION,
		FISH,
		GAME_PIECE1,
		GAME_PIECE2,
		GAME_PIECE3,
		ENEMY_PIECE,
		WHEEL_OF_FORTUNE,
		SCALES,
		DARTS,
		DART_EMITTER,
		HOMING_DART_EMITTER,
		FALLING_CEILING,
		FALLING_BLOCK,
		FALLING_BLOCK2,
		SMASHABLE_BIKE_WALL,
		SMASHABLE_BIKE_FLOOR,
		TRAPDOOR1,
		TRAPDOOR2,
		TRAPDOOR3,
		FLOOR_TRAPDOOR1,
		FLOOR_TRAPDOOR2,
		CEILING_TRAPDOOR1,
		CEILING_TRAPDOOR2,
		SCALING_TRAPDOOR,
		ROLLINGBALL,
		SPIKEY_FLOOR,
		TEETH_SPIKES,
		JOBY_SPIKES,
		SLICER_DICER,
		CHAIN,
		PLOUGH,
		STARGATE,
		HAMMER,
		BURNING_FLOOR,
		COG,
		SPIKEBALL,
		FLAME,
		FLAME_EMITTER,
		FLAME_EMITTER2,
		FLAME_EMITTER3,
		ROPE,
		FIREROPE,
		POLEROPE,
		ONEBLOCK_PLATFORM,
		TWOBLOCK_PLATFORM,
		RAISING_BLOCK1,
		RAISING_BLOCK2,
		EXPANDING_PLATFORM,
		SQUISHY_BLOCK1,
		SQUISHY_BLOCK2,
		PUSHABLE_OBJECT1,
		PUSHABLE_OBJECT2,
		PUSHABLE_OBJECT3,
		PUSHABLE_OBJECT4,
		PUSHABLE_OBJECT5,
		TRIPWIRE,
		SENTRY_GUN,
		MINE,
		MAPPER,
		OBELISK,
		FLOOR_4BLADE,
		ROOF_4BLADE,
		BIRD_BLADE,
		CATWALK_BLADE,
		MOVING_BLADE,
		PLINTH_BLADE,
		SETH_BLADE,
		LIGHTNING_CONDUCTOR,
		ELEMENT_PUZZLE,
		PUZZLE_ITEM1,
		PUZZLE_ITEM2,
		PUZZLE_ITEM3,
		PUZZLE_ITEM4,
		PUZZLE_ITEM5,
		PUZZLE_ITEM6,
		PUZZLE_ITEM7,
		PUZZLE_ITEM8,
		PUZZLE_ITEM9,
		PUZZLE_ITEM10,
		PUZZLE_ITEM11,
		PUZZLE_ITEM12,
		PUZZLE_ITEM1_COMBO1,
		PUZZLE_ITEM1_COMBO2,
		PUZZLE_ITEM2_COMBO1,
		PUZZLE_ITEM2_COMBO2,
		PUZZLE_ITEM3_COMBO1,
		PUZZLE_ITEM3_COMBO2,
		PUZZLE_ITEM4_COMBO1,
		PUZZLE_ITEM4_COMBO2,
		PUZZLE_ITEM5_COMBO1,
		PUZZLE_ITEM5_COMBO2,
		PUZZLE_ITEM6_COMBO1,
		PUZZLE_ITEM6_COMBO2,
		PUZZLE_ITEM7_COMBO1,
		PUZZLE_ITEM7_COMBO2,
		PUZZLE_ITEM8_COMBO1,
		PUZZLE_ITEM8_COMBO2,
		KEY_ITEM1,
		KEY_ITEM2,
		KEY_ITEM3,
		KEY_ITEM4,
		KEY_ITEM5,
		KEY_ITEM6,
		KEY_ITEM7,
		KEY_ITEM8,
		KEY_ITEM9,
		KEY_ITEM10,
		KEY_ITEM11,
		KEY_ITEM12,
		KEY_ITEM1_COMBO1,
		KEY_ITEM1_COMBO2,
		KEY_ITEM2_COMBO1,
		KEY_ITEM2_COMBO2,
		KEY_ITEM3_COMBO1,
		KEY_ITEM3_COMBO2,
		KEY_ITEM4_COMBO1,
		KEY_ITEM4_COMBO2,
		KEY_ITEM5_COMBO1,
		KEY_ITEM5_COMBO2,
		KEY_ITEM6_COMBO1,
		KEY_ITEM6_COMBO2,
		KEY_ITEM7_COMBO1,
		KEY_ITEM7_COMBO2,
		KEY_ITEM8_COMBO1,
		KEY_ITEM8_COMBO2,
		PICKUP_ITEM1,
		PICKUP_ITEM2,
		PICKUP_ITEM3,
		PICKUP_ITEM4,
		PICKUP_ITEM1_COMBO1,
		PICKUP_ITEM1_COMBO2,
		PICKUP_ITEM2_COMBO1,
		PICKUP_ITEM2_COMBO2,
		PICKUP_ITEM3_COMBO1,
		PICKUP_ITEM3_COMBO2,
		PICKUP_ITEM4_COMBO1,
		PICKUP_ITEM4_COMBO2,
		EXAMINE1,
		EXAMINE2,
		EXAMINE3,
		CROWBAR_ITEM,
		BURNING_TORCH_ITEM,
		CLOCKWORK_BEETLE,
		CLOCKWORK_BEETLE_COMBO1,
		CLOCKWORK_BEETLE_COMBO2,
		MINE_DETECTOR,
		QUEST_ITEM1,
		QUEST_ITEM2,
		QUEST_ITEM3,
		QUEST_ITEM4,
		QUEST_ITEM5,
		QUEST_ITEM6,
		MAP,
		SECRET_MAP,
		PUZZLE_HOLE1,
		PUZZLE_HOLE2,
		PUZZLE_HOLE3,
		PUZZLE_HOLE4,
		PUZZLE_HOLE5,
		PUZZLE_HOLE6,
		PUZZLE_HOLE7,
		PUZZLE_HOLE8,
		PUZZLE_HOLE9,
		PUZZLE_HOLE10,
		PUZZLE_HOLE11,
		PUZZLE_HOLE12,
		PUZZLE_DONE1,
		PUZZLE_DONE2,
		PUZZLE_DONE3,
		PUZZLE_DONE4,
		PUZZLE_DONE5,
		PUZZLE_DONE6,
		PUZZLE_DONE7,
		PUZZLE_DONE8,
		PUZZLE_DONE9,
		PUZZLE_DONE10,
		PUZZLE_DONE11,
		PUZZLE_DONE12,
		KEY_HOLE1,
		KEY_HOLE2,
		KEY_HOLE3,
		KEY_HOLE4,
		KEY_HOLE5,
		KEY_HOLE6,
		KEY_HOLE7,
		KEY_HOLE8,
		KEY_HOLE9,
		KEY_HOLE10,
		KEY_HOLE11,
		KEY_HOLE12,
		WATERSKIN1_EMPTY,
		WATERSKIN1_1,
		WATERSKIN1_2,
		WATERSKIN1_3,
		WATERSKIN2_EMPTY,
		WATERSKIN2_1,
		WATERSKIN2_2,
		WATERSKIN2_3,
		WATERSKIN2_4,
		WATERSKIN2_5,
		SWITCH_TYPE1,
		SWITCH_TYPE2,
		SWITCH_TYPE3,
		SWITCH_TYPE4,
		SWITCH_TYPE5,
		SWITCH_TYPE6,
		SWITCH_TYPE7,
		SWITCH_TYPE8,
		UNDERWATER_SWITCH1,
		UNDERWATER_SWITCH2,
		TURN_SWITCH,
		COG_SWITCH,
		LEVER_SWITCH,
		JUMP_SWITCH,
		CROWBAR_SWITCH,
		PULLEY,
		DOOR_TYPE1,
		DOOR_TYPE2,
		DOOR_TYPE3,
		DOOR_TYPE4,
		DOOR_TYPE5,
		DOOR_TYPE6,
		DOOR_TYPE7,
		DOOR_TYPE8,
		PUSHPULL_DOOR1,
		PUSHPULL_DOOR2,
		KICK_DOOR1,
		KICK_DOOR2,
		UNDERWATER_DOOR,
		DOUBLE_DOORS,
		BRIDGE_FLAT,
		BRIDGE_TILT1,
		BRIDGE_TILT2,
		SARCOPHAGUS,
		SEQUENCE_DOOR1,
		SEQUENCE_SWITCH1,
		SEQUENCE_SWITCH2,
		SEQUENCE_SWITCH3,
		SARCOPHAGUS_CUT,
		HORUS_STATUE,
		GOD_HEAD,
		SETH_DOOR,
		STATUE_PLINTH,
		PISTOLS_ITEM,
		PISTOLS_AMMO_ITEM,
		UZI_ITEM,
		UZI_AMMO_ITEM,
		SHOTGUN_ITEM,
		SHOTGUN_AMMO1_ITEM,
		SHOTGUN_AMMO2_ITEM,
		CROSSBOW_ITEM,
		CROSSBOW_AMMO1_ITEM,
		CROSSBOW_AMMO2_ITEM,
		CROSSBOW_AMMO3_ITEM,
		CROSSBOW_BOLT,
		GRENADE_GUN_ITEM,
		GRENADE_GUN_AMMO1_ITEM,
		GRENADE_GUN_AMMO2_ITEM,
		GRENADE_GUN_AMMO3_ITEM,
		GRENADE,
		SIXSHOOTER_ITEM,
		SIXSHOOTER_AMMO_ITEM,
		BIGMEDI_ITEM,
		SMALLMEDI_ITEM,
		LASERSIGHT_ITEM,
		BINOCULARS_ITEM,
		FLARE_ITEM,
		FLARE_INV_ITEM,
		DIARY_ITEM,
		COMPASS_ITEM,
		MEMCARD_LOAD_INV_ITEM,
		MEMCARD_SAVE_INV_ITEM,
		PC_LOAD_INV_ITEM,
		PC_SAVE_INV_ITEM,
		SMOKE_EMITTER_WHITE,
		SMOKE_EMITTER_BLACK,
		STEAM_EMITTER,
		EARTHQUAKE,
		BUBBLES,
		WATERFALLMIST,
		GUNSHELL,
		SHOTGUNSHELL,
		GUN_FLASH,
		BUTTERFLY,
		SPRINKLER,
		RED_LIGHT,
		GREEN_LIGHT,
		BLUE_LIGHT,
		AMBER_LIGHT,
		WHITE_LIGHT,
		BLINKING_LIGHT,
		LENS_FLARE,
		AI_GUARD,
		AI_AMBUSH,
		AI_PATROL1,
		AI_MODIFY,
		AI_FOLLOW,
		AI_PATROL2,
		AI_X1,
		AI_X2,
		LARA_START_POS,
		KILL_ALL_TRIGGERS,
		TRIGGER_TRIGGERER,
		SMASH_OBJECT1,
		SMASH_OBJECT2,
		SMASH_OBJECT3,
		SMASH_OBJECT4,
		SMASH_OBJECT5,
		SMASH_OBJECT6,
		SMASH_OBJECT7,
		SMASH_OBJECT8,
		MESHSWAP1,
		MESHSWAP2,
		MESHSWAP3,
		DEATH_SLIDE,
		BODY_PART,
		CAMERA_TARGET,
		WATERFALL1,
		WATERFALL2,
		WATERFALL3,
		PLANET_EFFECT,
		ANIMATING1,
		ANIMATING1_MIP,
		ANIMATING2,
		ANIMATING2_MIP,
		ANIMATING3,
		ANIMATING3_MIP,
		ANIMATING4,
		ANIMATING4_MIP,
		ANIMATING5,
		ANIMATING5_MIP,
		ANIMATING6,
		ANIMATING6_MIP,
		ANIMATING7,
		ANIMATING7_MIP,
		ANIMATING8,
		ANIMATING8_MIP,
		ANIMATING9,
		ANIMATING9_MIP,
		ANIMATING10,
		ANIMATING10_MIP,
		ANIMATING11,
		ANIMATING11_MIP,
		ANIMATING12,
		ANIMATING12_MIP,
		ANIMATING13,
		ANIMATING13_MIP,
		ANIMATING14,
		ANIMATING14_MIP,
		ANIMATING15,
		ANIMATING15_MIP,
		ANIMATING16,
		ANIMATING16_MIP,
		HORIZON,
		SKY_GRAPHICS,
		BINOCULAR_GRAPHICS,
		TARGET_GRAPHICS,
		DEFAULT_SPRITES,
		MISC_SPRITES,
		MOTOR_BOAT,
		MOTOR_BOAT_LARA,
		RUBBER_BOAT,
		RUBBER_BOAT_LARA,
		MOTORBIKE_LARA,
		FONT_GRAPHICS,
		PARALLEL_BARS,
		PANEL_BORDER,
		PANEL_MIDDLE,
		PANEL_CORNER,
		PANEL_DIAGONAL,
		PANEL_STRIP,
		PANEL_HALF_BORDER1,
		PANEL_HALF_BORDER2,
		PANEL_MIDDLE_CORNER,
		TIGHT_ROPE,
		LASER_HEAD,
		LASER_HEAD_BASE,
		LASER_HEAD_TENTACLE,
		HYDRA,
		HYDRA_MISSILE,
		ENEMY_SUB_MARINE,
		ENEMY_SUB_MARINE_MIP,
		SUB_MARINE_MISSILE,
		FROG_MAN,
		FROG_MAN_HARPOON,
		FISH_EMITTER,
		KAYAK,
		KAYAK_LARA,
		CUSTOM_SPRITES,
		BRIDGE_TILT3,
		BRIDGE_TILT4,
		BRIDGE_CUSTOM,
		ROBOT_CLEANER,
		ROBOT_STAR_WARS,
		MECH_WARRIOR,
		MECH_WARRIOR_LARA,
		UW_PROPULSOR,
		UW_PROPULSOR_LARA,
		MINE_CART,
		MINE_CART_LARA,
		NEW_SLOT5,
		NEW_SLOT6,
		NEW_SLOT7,
		NEW_SLOT8,
		NEW_SLOT9,
		NEW_SLOT10,
		NEW_SLOT11,
		NEW_SLOT12,
		NEW_SLOT13,
		NEW_SLOT14,
		NEW_SLOT15,
		NEW_SLOT16,
		NEW_SLOT17,
		NEW_SLOT18,
		NUMBER_OBJECTS
	};

	enum static_types
	{
		PLANT0,
		PLANT1,
		PLANT2,
		PLANT3,
		PLANT4,
		PLANT5,
		PLANT6,
		PLANT7,
		PLANT8,
		PLANT9,
		FURNITURE0,
		FURNITURE1,
		FURNITURE2,
		FURNITURE3,
		FURNITURE4,
		FURNITURE5,
		FURNITURE6,
		FURNITURE7,
		FURNITURE8,
		FURNITURE9,
		ROCK0,
		ROCK1,
		ROCK2,
		ROCK3,
		ROCK4,
		ROCK5,
		ROCK6,
		ROCK7,
		ROCK8,
		ROCK9,
		ARCHITECTURE0,
		ARCHITECTURE1,
		ARCHITECTURE2,
		ARCHITECTURE3,
		ARCHITECTURE4,
		ARCHITECTURE5,
		ARCHITECTURE6,
		ARCHITECTURE7,
		ARCHITECTURE8,
		ARCHITECTURE9,
		DEBRIS0,
		DEBRIS1,
		DEBRIS2,
		DEBRIS3,
		DEBRIS4,
		DEBRIS5,
		DEBRIS6,
		DEBRIS7,
		DEBRIS8,
		DEBRIS9,
		SHATTER0,
		SHATTER1,
		SHATTER2,
		SHATTER3,
		SHATTER4,
		SHATTER5,
		SHATTER6,
		SHATTER7,
		SHATTER8,
		SHATTER9,
		EXTRA00,
		EXTRA01,
		EXTRA02,
		EXTRA03,
		EXTRA04,
		EXTRA05,
		EXTRA06,
		EXTRA07,
		EXTRA08,
		EXTRA09,
		EXTRA10,
		EXTRA11,
		EXTRA12,
		EXTRA13,
		EXTRA14,
		EXTRA15,
		EXTRA16,
		EXTRA17,
		EXTRA18,
		EXTRA19,
		EXTRA20,
		EXTRA21,
		EXTRA22,
		EXTRA23,
		EXTRA24,
		EXTRA25,
		EXTRA26,
		EXTRA27,
		EXTRA28,
		EXTRA29,
		EXTRA30,
		EXTRA31,
		EXTRA32,
		EXTRA33,
		EXTRA34,
		EXTRA35,
		EXTRA36,
		EXTRA37,
		EXTRA38,
		EXTRA39,
		EXTRA40,
		EXTRA41,
		EXTRA42,
		EXTRA43,
		EXTRA44,
		EXTRA45,
		EXTRA46,
		EXTRA47,
		EXTRA48,
		EXTRA49,
		EXTRA50,
		EXTRA51,
		EXTRA52,
		EXTRA53,
		EXTRA54,
		EXTRA55,
		EXTRA56,
		EXTRA57,
		EXTRA58,
		EXTRA59,
		EXTRA60,
		EXTRA61,
		EXTRA62,
		EXTRA63,
		EXTRA64,
		EXTRA65,
		EXTRA66,
		EXTRA67,
		EXTRA68,
		EXTRA69,
		EXTRA70,
		EXTRA71,
		EXTRA72,
		EXTRA73,
		EXTRA74,
		EXTRA75,
		EXTRA76,
		EXTRA77,
		EXTRA78,
		EXTRA79,
		EXTRA80,
		EXTRA81,
		EXTRA82,
		EXTRA83,
		EXTRA84,
		EXTRA85,
		EXTRA86,
		EXTRA87,
		EXTRA88,
		EXTRA89,
		EXTRA90,
		EXTRA91,
		EXTRA92,
		EXTRA93,
		EXTRA94,
		EXTRA95,
		EXTRA96,
		EXTRA97,
		EXTRA98,
		EXTRA99,
		EXTRA100,
		EXTRA101,
		EXTRA102,
		EXTRA103,
		EXTRA104,
		EXTRA105,
		EXTRA106,
		EXTRA107,
		EXTRA108,
		EXTRA109,
		EXTRA110,
		EXTRA111,
		EXTRA112,
		EXTRA113,
		EXTRA114,
		EXTRA115,
		EXTRA116,
		EXTRA117,
		EXTRA118,
		EXTRA119,
		EXTRA120,
		EXTRA121,
		EXTRA122,
		EXTRA123,
		EXTRA124,
		EXTRA125,
		EXTRA126,
		EXTRA127,
		EXTRA128,
		EXTRA129,
		EXTRA130,
		EXTRA131,
		EXTRA132,
		EXTRA133,
		EXTRA134,
		EXTRA135,
		EXTRA136,
		EXTRA137,
		EXTRA138,
		EXTRA139,
		EXTRA140,
		EXTRA141,
		EXTRA142,
		EXTRA143,
		EXTRA144,
		EXTRA145,
		EXTRA146,
		EXTRA147,
		EXTRA148,
		EXTRA149,
		EXTRA150,
		EXTRA151,
		EXTRA152,
		EXTRA153,
		EXTRA154,
		EXTRA155,
		EXTRA156,
		EXTRA157,
		EXTRA158,
		EXTRA159,
		EXTRA160,
		EXTRA161,
		EXTRA162,
		EXTRA163,
		EXTRA164,
		EXTRA165,
		EXTRA166,
		EXTRA167,
		EXTRA168,
		EXTRA169,
		EXTRA170,
		EXTRA171,
		EXTRA172,
		EXTRA173,
		EXTRA174,
		EXTRA175,
		EXTRA176,
		EXTRA177,
		EXTRA178,
		EXTRA179,
		NUMBER_STATIC_OBJECTS
	};

	enum ITEM_FLAGS
	{
		IFL_TRIGGERED = 0x20,
		IFL_SWITCH_ONESHOT = 0x40,	//oneshot for switch items
		IFL_ANTITRIGGER_ONESHOT = 0x80,	//oneshot for antitriggers
		IFL_INVISIBLE = 0x100,	//also used as oneshot for everything else
		IFL_CODEBITS = 0x3E00,
		IFL_REVERSE = 0x4000,
		IFL_CLEARBODY = 0x8000
	};

	enum camera_type
	{
		CHASE_CAMERA,
		FIXED_CAMERA,
		LOOK_CAMERA,
		COMBAT_CAMERA,
		CINEMATIC_CAMERA,
		HEAVY_CAMERA
	};

	enum invobj_types
	{
		INV_UZI_ITEM,
		INV_PISTOLS_ITEM,
		INV_SHOTGUN_ITEM,
		INV_REVOLVER_ITEM,
		INV_REVOLVER_LASER_ITEM,
		INV_CROSSBOW_ITEM,
		INV_CROSSBOW_LASER_ITEM,
		INV_GRENADEGUN_ITEM,
		INV_SHOTGUN_AMMO1_ITEM,
		INV_SHOTGUN_AMMO2_ITEM,
		INV_GRENADEGUN_AMMO1_ITEM,
		INV_GRENADEGUN_AMMO2_ITEM,
		INV_GRENADEGUN_AMMO3_ITEM,
		INV_CROSSBOW_AMMO1_ITEM,
		INV_CROSSBOW_AMMO2_ITEM,
		INV_CROSSBOW_AMMO3_ITEM,
		INV_REVOLVER_AMMO_ITEM,
		INV_UZI_AMMO_ITEM,
		INV_PISTOLS_AMMO_ITEM,
		INV_LASERSIGHT_ITEM,
		INV_BIGMEDI_ITEM,
		INV_SMALLMEDI_ITEM,
		INV_BINOCULARS_ITEM,
		INV_FLARE_INV_ITEM,
		INV_COMPASS_ITEM,
		INV_MEMCARD_LOAD_ITEM,
		INV_MEMCARD_SAVE_ITEM,
		INV_WATERSKIN1_EMPTY_ITEM,
		INV_WATERSKIN1_1_ITEM,
		INV_WATERSKIN1_2_ITEM,
		INV_WATERSKIN1_3_ITEM,
		INV_WATERSKIN2_EMPTY_ITEM,
		INV_WATERSKIN2_1_ITEM,
		INV_WATERSKIN2_2_ITEM,
		INV_WATERSKIN2_3_ITEM,
		INV_WATERSKIN2_4_ITEM,
		INV_WATERSKIN2_5_ITEM,
		INV_PUZZLE1_ITEM,
		INV_PUZZLE2_ITEM,
		INV_PUZZLE3_ITEM,
		INV_PUZZLE4_ITEM,
		INV_PUZZLE5_ITEM,
		INV_PUZZLE6_ITEM,
		INV_PUZZLE7_ITEM,
		INV_PUZZLE8_ITEM,
		INV_PUZZLE9_ITEM,
		INV_PUZZLE10_ITEM,
		INV_PUZZLE11_ITEM,
		INV_PUZZLE12_ITEM,
		INV_PUZZLE1_COMBO1_ITEM,
		INV_PUZZLE1_COMBO2_ITEM,
		INV_PUZZLE2_COMBO1_ITEM,
		INV_PUZZLE2_COMBO2_ITEM,
		INV_PUZZLE3_COMBO1_ITEM,
		INV_PUZZLE3_COMBO2_ITEM,
		INV_PUZZLE4_COMBO1_ITEM,
		INV_PUZZLE4_COMBO2_ITEM,
		INV_PUZZLE5_COMBO1_ITEM,
		INV_PUZZLE5_COMBO2_ITEM,
		INV_PUZZLE6_COMBO1_ITEM,
		INV_PUZZLE6_COMBO2_ITEM,
		INV_PUZZLE7_COMBO1_ITEM,
		INV_PUZZLE7_COMBO2_ITEM,
		INV_PUZZLE8_COMBO1_ITEM,
		INV_PUZZLE8_COMBO2_ITEM,
		INV_KEY1_ITEM,
		INV_KEY2_ITEM,
		INV_KEY3_ITEM,
		INV_KEY4_ITEM,
		INV_KEY5_ITEM,
		INV_KEY6_ITEM,
		INV_KEY7_ITEM,
		INV_KEY8_ITEM,
		INV_KEY9_ITEM,
		INV_KEY10_ITEM,
		INV_KEY11_ITEM,
		INV_KEY12_ITEM,
		INV_KEY1_COMBO1_ITEM,
		INV_KEY1_COMBO2_ITEM,
		INV_KEY2_COMBO1_ITEM,
		INV_KEY2_COMBO2_ITEM,
		INV_KEY3_COMBO1_ITEM,
		INV_KEY3_COMBO2_ITEM,
		INV_KEY4_COMBO1_ITEM,
		INV_KEY4_COMBO2_ITEM,
		INV_KEY5_COMBO1_ITEM,
		INV_KEY5_COMBO2_ITEM,
		INV_KEY6_COMBO1_ITEM,
		INV_KEY6_COMBO2_ITEM,
		INV_KEY7_COMBO1_ITEM,
		INV_KEY7_COMBO2_ITEM,
		INV_KEY8_COMBO1_ITEM,
		INV_KEY8_COMBO2_ITEM,
		INV_PICKUP1_ITEM,
		INV_PICKUP2_ITEM,
		INV_PICKUP3_ITEM,
		INV_PICKUP4_ITEM,
		INV_PICKUP1_COMBO1_ITEM,
		INV_PICKUP1_COMBO2_ITEM,
		INV_PICKUP2_COMBO1_ITEM,
		INV_PICKUP2_COMBO2_ITEM,
		INV_PICKUP3_COMBO1_ITEM,
		INV_PICKUP3_COMBO2_ITEM,
		INV_PICKUP4_COMBO1_ITEM,
		INV_PICKUP4_COMBO2_ITEM,
		INV_QUEST1_ITEM,
		INV_QUEST2_ITEM,
		INV_QUEST3_ITEM,
		INV_QUEST4_ITEM,
		INV_QUEST5_ITEM,
		INV_QUEST6_ITEM,
		INV_BURNING_TORCH_ITEM,
		INV_CROWBAR_ITEM,
		INV_CLOCKWORK_BEETLE_ITEM,
		INV_MECHANICAL_SCARAB_ITEM,
		INV_WINDING_KEY_ITEM,
		INV_EXAMINE1_ITEM,
		INV_EXAMINE2_ITEM,
		INV_EXAMINE3_ITEM,
		NUM_INVOBJ
	};

	enum gf_commands
	{
		CMD_FMV = 0x80,
		CMD_LEVEL,
		CMD_TITLE,
		CMD_ENDSEQ,
		CMD_PLAYCUT,
		CMD_CUT1,
		CMD_CUT2,
		CMD_CUT3,
		CMD_CUT4,
		CMD_LAYER1,
		CMD_LAYER2,
		CMD_UVROT,
		CMD_LEGEND,
		CMD_LENSFLARE,
		CMD_MIRROR,
		CMD_FOG,
		CMD_ANIMATINGMIP,
		CMD_CAMERA,
		CMD_RESETHUB,
		CMD_KEY1,
		CMD_KEY2,
		CMD_KEY3,
		CMD_KEY4,
		CMD_KEY5,
		CMD_KEY6,
		CMD_KEY7,
		CMD_KEY8,
		CMD_KEY9,
		CMD_KEY10,
		CMD_KEY11,
		CMD_KEY12,
		CMD_PUZZLE1,
		CMD_PUZZLE2,
		CMD_PUZZLE3,
		CMD_PUZZLE4,
		CMD_PUZZLE5,
		CMD_PUZZLE6,
		CMD_PUZZLE7,
		CMD_PUZZLE8,
		CMD_PUZZLE9,
		CMD_PUZZLE10,
		CMD_PUZZLE11,
		CMD_PUZZLE12,
		CMD_PICKUP1,
		CMD_PICKUP2,
		CMD_PICKUP3,
		CMD_PICKUP4,
		CMD_EXAMINE1,
		CMD_EXAMINE2,
		CMD_EXAMINE3,
		CMD_KEYCOMBO1_1,
		CMD_KEYCOMBO1_2,
		CMD_KEYCOMBO2_1,
		CMD_KEYCOMBO2_2,
		CMD_KEYCOMBO3_1,
		CMD_KEYCOMBO3_2,
		CMD_KEYCOMBO4_1,
		CMD_KEYCOMBO4_2,
		CMD_KEYCOMBO5_1,
		CMD_KEYCOMBO5_2,
		CMD_KEYCOMBO6_1,
		CMD_KEYCOMBO6_2,
		CMD_KEYCOMBO7_1,
		CMD_KEYCOMBO7_2,
		CMD_KEYCOMBO8_1,
		CMD_KEYCOMBO8_2,
		CMD_PUZZLECOMBO1_1,
		CMD_PUZZLECOMBO1_2,
		CMD_PUZZLECOMBO2_1,
		CMD_PUZZLECOMBO2_2,
		CMD_PUZZLECOMBO3_1,
		CMD_PUZZLECOMBO3_2,
		CMD_PUZZLECOMBO4_1,
		CMD_PUZZLECOMBO4_2,
		CMD_PUZZLECOMBO5_1,
		CMD_PUZZLECOMBO5_2,
		CMD_PUZZLECOMBO6_1,
		CMD_PUZZLECOMBO6_2,
		CMD_PUZZLECOMBO7_1,
		CMD_PUZZLECOMBO7_2,
		CMD_PUZZLECOMBO8_1,
		CMD_PUZZLECOMBO8_2,
		CMD_PICKUPCOMBO1_1,
		CMD_PICKUPCOMBO1_2,
		CMD_PICKUPCOMBO2_1,
		CMD_PICKUPCOMBO2_2,
		CMD_PICKUPCOMBO3_1,
		CMD_PICKUPCOMBO3_2,
		CMD_PICKUPCOMBO4_1,
		CMD_PICKUPCOMBO4_2
	};

	enum gf_level_options
	{
		GF_YOUNGLARA = 0x1,
		GF_WEATHER = 0x2,
		GF_HORIZON = 0x4,
		GF_LAYER1 = 0x8,
		GF_LAYER2 = 0x10,
		GF_STARFIELD = 0x20,
		GF_LIGHTNING = 0x40,
		GF_TRAIN = 0x80,
		GF_PULSE = 0x100,
		GF_HORIZONCOLADD = 0x200,
		GF_RESETHUB = 0x400,
		GF_LENSFLARE = 0x800,
		GF_TIMER = 0x1000,
		GF_MIRROR = 0x2000,
		GF_REMOVEAMULET = 0x4000,
		GF_NOLEVEL = 0x8000
	};

	enum input_buttons
	{
		IN_NONE = 0x0,
		IN_FORWARD = 0x1,
		IN_BACK = 0x2,
		IN_LEFT = 0x4,
		IN_RIGHT = 0x8,
		IN_JUMP = 0x10,
		IN_DRAW = 0x20,
		IN_ACTION = 0x40,
		IN_WALK = 0x80,
		IN_OPTION = 0x100,
		IN_LOOK = 0x200,
		IN_LSTEP = 0x400,
		IN_RSTEP = 0x800,
		IN_ROLL = 0x1000,
		IN_PAUSE = 0x2000,
		IN_A = 0x4000,
		IN_B = 0x8000,
		IN_CHEAT = 0x10000,
		IN_D = 0x20000,
		IN_C = 0x30000,
		IN_E = 0x40000,
		IN_FLARE = 0x80000,
		IN_SELECT = 0x100000,
		IN_DESELECT = 0x200000,
		IN_SAVE = 0x400000,
		IN_LOAD = 0x800000,
		IN_STEPSHIFT = 0x1000000,
		IN_LOOKLEFT = 0x2000000,
		IN_LOOKRIGHT = 0x4000000,
		IN_LOOKFORWARD = 0x8000000,
		IN_LOOKBACK = 0x10000000,
		IN_DUCK = 0x20000000,
		IN_SPRINT = 0x40000000,
		IN_TARGET = (long)0x80000000,
		IN_ALL = (long)0xFFFFFFFF
	};

	enum lara_anim_state
	{
		AS_WALK = 0,
		AS_RUN = 1,
		AS_STOP = 2,
		AS_FORWARDJUMP = 3,
		AS_POSE = 4,
		AS_FASTBACK = 5,
		AS_TURN_R = 6,
		AS_TURN_L = 7,
		AS_DEATH = 8,
		AS_FASTFALL = 9,
		AS_HANG = 10,
		AS_REACH = 11,
		AS_SPLAT = 12,
		AS_TREAD = 13,
		AS_LAND = 14,
		AS_COMPRESS = 15,
		AS_BACK = 16,
		AS_SWIM = 17,
		AS_GLIDE = 18,
		AS_NULL = 19,
		AS_FASTTURN = 20,
		AS_STEPRIGHT = 21,
		AS_STEPLEFT = 22,
		AS_HIT = 23,
		AS_SLIDE = 24,
		AS_BACKJUMP = 25,
		AS_RIGHTJUMP = 26,
		AS_LEFTJUMP = 27,
		AS_UPJUMP = 28,
		AS_FALLBACK = 29,
		AS_HANGLEFT = 30,
		AS_HANGRIGHT = 31,
		AS_SLIDEBACK = 32,
		AS_SURFTREAD = 33,
		AS_SURFSWIM = 34,
		AS_DIVE = 35,
		AS_PUSHBLOCK = 36,
		AS_PULLBLOCK = 37,
		AS_PPREADY = 38,
		AS_PICKUP = 39,
		AS_SWITCHON = 40,
		AS_SWITCHOFF = 41,
		AS_USEKEY = 42,
		AS_USEPUZZLE = 43,
		AS_UWDEATH = 44,
		AS_ROLL = 45,
		AS_SPECIAL = 46,
		AS_SURFBACK = 47,
		AS_SURFLEFT = 48,
		AS_SURFRIGHT = 49,
		AS_USEMIDAS = 50,
		AS_DIEMIDAS = 51,
		AS_SWANDIVE = 52,
		AS_FASTDIVE = 53,
		AS_GYMNAST = 54,
		AS_WATEROUT = 55,
		AS_CLIMBSTNC = 56,
		AS_CLIMBING = 57,
		AS_CLIMBLEFT = 58,
		AS_CLIMBEND = 59,
		AS_CLIMBRIGHT = 60,
		AS_CLIMBDOWN = 61,
		AS_LARATEST1 = 62,
		AS_LARATEST2 = 63,
		AS_LARATEST3 = 64,
		AS_WADE = 65,
		AS_WATERROLL = 66,
		AS_FLAREPICKUP = 67,
		AS_TWIST = 68,
		AS_KICK = 69,
		AS_DEATHSLIDE = 70,
		AS_DUCK = 71,
		AS_DUCKROLL = 72,
		AS_DASH = 73,
		AS_DASHDIVE = 74,
		AS_HANG2 = 75,
		AS_MONKEYSWING = 76,
		AS_MONKEYL = 77,
		AS_MONKEYR = 78,
		AS_MONKEY180 = 79,
		AS_ALL4S = 80,
		AS_CRAWL = 81,
		AS_HANGTURNL = 82,
		AS_HANGTURNR = 83,
		AS_ALL4TURNL = 84,
		AS_ALL4TURNR = 85,
		AS_CRAWLBACK = 86,
		AS_HANG2DUCK = 87,
		AS_CRAWL2HANG = 88,
		AS_CONTROLLED = 89,
		AS_ROPELEFT = 90,
		AS_ROPERIGHT = 91,
		AS_BLOCKSWITCH = 92,
		AS_LIFTTRAP = 93,
		AS_PULLTRAP = 94,
		AS_TURNSWITCH = 95,
		AS_COGSWITCH = 96,
		AS_RAILSWITCH = 97,
		AS_HIDDENPICKUP = 98,
		AS_POLESTAT = 99,
		AS_POLEUP = 100,
		AS_POLEDOWN = 101,
		AS_POLELEFT = 102,
		AS_POLERIGHT = 103,
		AS_PULLEY = 104,
		AS_DUCKROTL = 105,
		AS_DUCKROTR = 106,
		AS_CORNEREXTL = 107,
		AS_CORNEREXTR = 108,
		AS_CORNERINTL = 109,
		AS_CORNERINTR = 110,
		AS_ROPE = 111,
		AS_CLIMBROPE = 112,
		AS_SLIDEROPE = 113,
		AS_ROPEFWD = 114,
		AS_ROPEBACK = 115,
		AS_MOVE = 116,
		AS_TWODOOR = 117,
		NUM_LARA_STATES
	};

	enum lara_anim
	{
		ANIM_RUN = 0,
		ANIM_WALK_STOP_LEFT = 2,
		ANIM_WALK_STOP_RIGHT = 3,
		ANIM_STARTRUN = 6,
		ANIM_STOP = 11,
		ANIM_FASTFALL = 23,
		ANIM_LANDFAR = 24,
		ANIM_STOPHANG = 28,
		ANIM_LAND = 31,
		ANIM_FASTSPLAT = 32,
		ANIM_FALLDOWN = 34,
		ANIM_VAULT3 = 42,
		ANIM_VAULT2 = 50,
		ANIM_HITWALLLEFT = 53,
		ANIM_HITWALLRIGHT = 54,
		ANIM_RUNSTEPUP_RIGHT = 55,
		ANIM_RUNSTEPUP_LEFT = 56,
		ANIM_WALKSTEPUP_LEFT = 57,
		ANIM_WALKSTEPUP_RIGHT = 58,
		ANIM_WALKSTEPD_RIGHT = 59,
		ANIM_WALKSTEPD_LEFT = 60,
		ANIM_BACKSTEPD_LEFT = 61,
		ANIM_BACKSTEPD_RIGHT = 62,
		ANIM_SWITCHOFF = 63,
		ANIM_SWITCHON = 64,
		ANIM_SLIDE = 70,
		ANIM_SWIMCHEAT = 87,
		ANIM_FALLBACK = 93,
		ANIM_GRABLOOP = 95,
		ANIM_GRABLEDGE = 96,
		ANIM_BREATH = 103,
		ANIM_SLIDEBACK = 104,
		ANIM_TREAD = 108,
		ANIM_SURFCLIMB = 111,
		ANIM_SURFDIVE = 119,
		ANIM_PPREADY = 120,
		ANIM_PULL = 122,
		ANIM_PUSH = 123,
		ANIM_JERK_FORWARD = 125,
		ANIM_JERK_BACK = 126,
		ANIM_JERK_RIGHT = 127,
		ANIM_JERK_LEFT = 128,
		ANIM_PICKUP_UW = 130,
		ANIM_USEKEY = 131,
		ANIM_USEPUZZLE = 134,
		ANIM_PICKUP = 135,
		ANIM_FBLOCK_DEATH = 138,
		ANIM_RBALL_DEATH = 139,
		ANIM_ROLL = 146,
		ANIM_SPIKED = 149,
		ANIM_HANG2STOP = 150,
		ANIM_CLIMBING = 161,
		ANIM_CLIMBSTNC = 164,
		ANIM_CLIMBDOWN = 168,
		ANIM_WADE = 177,
		ANIM_HANGUP = 187,
		ANIM_HANGDOWN = 188,
		ANIM_THROWFLARE = 189,
		ANIM_SURF2WADE1 = 190,
		ANIM_SURF2STND = 191,
		ANIM_SWIM2QSTND = 192,
		ANIM_SURF2QSTND = 193,
		ANIM_GENERATORSW_OFF = 195,
		ANIM_GENERATORSW_ON = 196,
		ANIM_ONEHANDPUSHSW = 197,
		ANIM_GRABRIGHT = 201,
		ANIM_GRABLEFT = 202,
		ANIM_WATERROLL = 203,
		ANIM_PICKUPF = 204,
		ANIM_PICKUPF_UW = 206,
		ANIM_DUCKBREATHE = 222,
		ANIM_UPJUMPGRAB = 233,
		ANIM_MONKEYHANG = 234,
		ANIM_DUCK_TO_ALL4S = 258,
		ANIM_ALL4S = 263,
		ANIM_ALL4S2 = 264,
		ANIM_ALL4TURNL = 269,
		ANIM_ALL4TURNR = 270,
		ANIM_DUCKPICKUP = 291,
		ANIM_JERK_DUCKB = 293,
		ANIM_JERK_DUCKF = 294,
		ANIM_JERK_DUCKR = 295,
		ANIM_JERK_DUCKL = 296,
		ANIM_CRAWL_TO_HANG = 302,
		ANIM_DUCKPICKUPF = 312,
		ANIM_PUSHDOOR = 313,
		ANIM_PULLDOOR = 314,
		ANIM_KICKDOOR = 315,
		ANIM_BLOCKSWITCH = 316,
		ANIM_LIFTTRAP = 317,
		ANIM_PULLTRAP = 318,
		ANIM_TURNSWITCHC = 319,
		ANIM_TURNSWITCHA = 320,
		ANIM_COGSWITCHL = 321,
		ANIM_COGSWITCHS = 322,
		ANIM_COGSWITCHE = 323,
		ANIM_RAILSWITCH = 324,
		ANIM_HIDDENPICKUP = 325,
		ANIM_STAT2POLE = 326,
		ANIM_POLESTAT = 328,
		ANIM_REACH2POLE = 331,
		ANIM_POLESLIDEE = 336,
		ANIM_JUMP2POLE = 337,
		ANIM_STAT2PULLEY = 339,
		ANIM_PULLEY = 340,
		ANIM_PULLEY2STAT = 341,
		ANIM_TURNSWITCHCB = 347,
		ANIM_TURNSWITCHCC = 348,
		ANIM_TURNSWITCHCD = 349,
		ANIM_TURNSWITCHAB = 350,
		ANIM_TURNSWITCHAC = 351,
		ANIM_TURNSWITCHAD = 352,
		ANIM_EXTCORNERL_END = 356,
		ANIM_EXTCORNERR_END = 358,
		ANIM_INTCORNERL_END = 360,
		ANIM_INTCORNERR_END = 362,
		ANIM_EXTCLIMBL = 363,
		ANIM_EXTCLIMBL_END = 364,
		ANIM_EXTCLIMBR = 365,
		ANIM_EXTCLIMBR_END = 366,
		ANIM_INTCLIMBL = 367,
		ANIM_INTCLIMBL_END = 368,
		ANIM_INTCLIMBR = 369,
		ANIM_INTCLIMBR_END = 370,
		ANIM_UPJUMP2ROPE = 371,
		ANIM_TRAINDEATH = 372,
		ANIM_SWING2HANG = 373,
		ANIM_ROPESLIDEL = 384,
		ANIM_ROPEKICK = 387,
		ANIM_SWINGFWD = 394,
		ANIM_POURWATERSKIN = 400,
		ANIM_FILLWATERSKIN = 401,
		ANIM_FILLSCALE = 402,
		ANIM_CROWBARDOOR = 403,
		ANIM_TWODOOR = 412,
		ANIM_SMALLSWITCH = 413,
		ANIM_LEAPSWITCH = 414,
		ANIM_WATERSWITCH = 415,
		ANIM_WATERDOOR = 416,
		ANIM_CROWBAR = 419,
		ANIM_CROWSWITCH = 420,
		ANIM_CRAWLJUMP = 421,
		ANIM_PLAYHARP = 422,
		ANIM_PLINTHHI = 424,
		ANIM_PLINTHLO = 425,
		ANIM_THROWSTIX = 426,
		ANIM_LIGHT_TORCH1 = 427,
		ANIM_LIGHT_TORCH2 = 428,
		ANIM_LIGHT_TORCH3 = 429,
		ANIM_LIGHT_TORCH4 = 430,
		ANIM_LIGHT_TORCH5 = 431,
		ANIM_MINEDETECT = 432,
		ANIM_MINEDEATH = 438,
		ANIM_SARCOPHAGUS = 439,
		ANIM_DRAGSAS = 440,
		ANIM_BINOCS = 441,
		ANIM_SETHDEATH = 443,
		ANIM_USEBEETLE = 444,
		NUM_LARA_ANIMS
	};

	enum weapon_types
	{
		WEAPON_NONE,
		WEAPON_PISTOLS,
		WEAPON_REVOLVER,
		WEAPON_UZI,
		WEAPON_SHOTGUN,
		WEAPON_GRENADE,
		WEAPON_CROSSBOW,
		WEAPON_FLARE,
		WEAPON_TORCH
	};

	enum lara_gun_status
	{
		LG_NO_ARMS,
		LG_HANDS_BUSY,
		LG_DRAW_GUNS,
		LG_UNDRAW_GUNS,
		LG_READY,
		LG_FLARE
	};

	enum lara_water_status
	{
		LW_ABOVE_WATER,
		LW_UNDERWATER,
		LW_SURFACE,
		LW_FLYCHEAT,
		LW_WADE
	};

	enum room_flags
	{
		ROOM_UNDERWATER = 0x1,
		ROOM_IS_FLIPROOM = 0x2,
		ROOM_QUICKSAND = 0x4,
		ROOM_OUTSIDE = 0x8,
		ROOM_DYNAMIC_LIT = 0x10,
		ROOM_NOT_INSIDE = 0x20,
		ROOM_INSIDE = 0x40,
		ROOM_NO_LENSFLARE = 0x80,
		ROOM_MIST = 0x100,
		ROOM_REFLECTION = 0x200,
		ROOM_SNOW = 0x400,
		ROOM_RAIN = 0x800,
		ROOM_COLD = 0x1000
	};

#pragma pack(push, 1)
	struct PHD_3DPOS
	{
		long x_pos;
		long y_pos;
		long z_pos;
		short x_rot;
		short y_rot;
		short z_rot;
	};

	struct LOCUST_STRUCT
	{
		PHD_3DPOS pos;
		short room_number;
		short speed;
		short Counter;
		short LaraTarget;
		char XTarget;
		char ZTarget;
		uchar On;
		uchar flags;
	};

	struct PHD_VECTOR
	{
		long x;
		long y;
		long z;
	};

	struct PCLIGHT
	{
		float x;
		float y;
		float z;
		float r;
		float g;
		float b;
		long shadow;
		float Inner;
		float Outer;
		float InnerAngle;
		float OuterAngle;
		float Cutoff;
		float nx;
		float ny;
		float nz;
		long ix;
		long iy;
		long iz;
		long inx;
		long iny;
		long inz;
		float tr;
		float tg;
		float tb;
		float rs;
		float gs;
		float bs;
		long fcnt;
		uchar Type;
		uchar Active;
		PHD_VECTOR rlp;
		long Range;
	};

	struct ITEM_LIGHT
	{
		long r;
		long g;
		long b;
		long ambient;
		long rs;
		long gs;
		long bs;
		long fcnt;
		PCLIGHT	CurrentLights[21];
		PCLIGHT	PrevLights[21];
		long nCurrentLights;
		long nPrevLights;
		long room_number;
		long RoomChange;
		PHD_VECTOR item_pos;
		void* pCurrentLights;
		void* pPrevLights;
	};

	struct ITEM_INFO
	{
		long floor;
		ulong touch_bits;
		ulong mesh_bits;
		short object_number;
		short current_anim_state;
		short goal_anim_state;
		short required_anim_state;
		short anim_number;
		short frame_number;
		short room_number;
		short next_item;
		short next_active;
		short speed;
		short fallspeed;
		short hit_points;
		ushort box_number;
		short timer;
		short flags;
		short shade;
		short trigger_flags;
		short carried_item;
		short after_death;
		ushort fired_weapon;
		short item_flags[4];
		void* data;
		PHD_3DPOS pos;
		ITEM_LIGHT il;
		ulong active : 1;
		ulong status : 2;
		ulong gravity_status : 1;
		ulong hit_status : 1;
		ulong collidable : 1;
		ulong looked_at : 1;
		ulong dynamic_light : 1;
		ulong poisoned : 1;
		ulong ai_bits : 5;
		ulong really_active : 1;
		ulong meshswap_meshbits;
		short draw_room;
		short TOSSPAD;
	};

	struct FX_INFO
	{
		PHD_3DPOS pos;
		short room_number;
		short object_number;
		short next_fx;
		short next_active;
		short speed;
		short fallspeed;
		short frame_number;
		short counter;
		short shade;
		short flag1;
		short flag2;
	};

	struct LARA_ARM
	{
		short* frame_base;
		short frame_number;
		short anim_number;
		short lock;
		short y_rot;
		short x_rot;
		short z_rot;
		short flash_gun;
	};

	struct BOX_NODE
	{
		short exit_box;
		ushort search_number;
		short next_expansion;
		short box_number;
	};

	struct LOT_INFO
	{
		BOX_NODE* node;
		short head;
		short tail;
		ushort search_number;
		ushort block_mask;
		short step;
		short drop;
		short zone_count;
		short target_box;
		short required_box;
		short fly;
		ushort can_jump : 1;
		ushort can_monkey : 1;
		ushort is_amphibious : 1;
		ushort is_jumping : 1;
		ushort is_monkeying : 1;
		PHD_VECTOR target;
		zone_type zone;
	};

	struct CREATURE_INFO
	{
		short joint_rotation[4];
		short maximum_turn;
		short flags;
		ushort alerted : 1;
		ushort head_left : 1;
		ushort head_right : 1;
		ushort reached_goal : 1;
		ushort hurt_by_lara : 1;
		ushort patrol2 : 1;
		ushort jump_ahead : 1;
		ushort monkey_ahead : 1;
		mood_type mood;
		ITEM_INFO* enemy;
		ITEM_INFO ai_target;
		short pad;
		short item_num;
		PHD_VECTOR target;
		LOT_INFO LOT;
	};

	struct LARA_INFO
	{
		short item_number;
		short gun_status;
		short gun_type;
		short request_gun_type;
		short last_gun_type;
		short calc_fallspeed;
		short water_status;
		short climb_status;
		short pose_count;
		short hit_frame;
		short hit_direction;
		short air;
		short dive_count;
		short death_count;
		short current_active;
		short current_xvel;
		short current_yvel;
		short current_zvel;
		short spaz_effect_count;
		short flare_age;
		short vehicle;
		short weapon_item;
		short back_gun;
		short flare_frame;
		short poisoned;
		short dpoisoned;

		union
		{
			struct
			{
				uchar electric;
				uchar wet[15];
			};

			uchar drip[16];
		};

		union
		{
			struct
			{
				ushort flare_control_left : 1;
				ushort Unused1 : 1;
				ushort look : 1;
				ushort burn : 1;
				ushort keep_ducked : 1;
				ushort IsMoving : 1;
				ushort CanMonkeySwing : 1;
				ushort Unused2 : 1;
				ushort OnBeetleFloor : 1;
				ushort BurnGreen : 1;
				ushort IsDucked : 1;
				ushort has_fired : 1;
				ushort Busy : 1;
				ushort LitTorch : 1;
				ushort IsClimbing : 1;
				ushort Fired : 1;
			};

			ushort bitfield;
		};

		long water_surface_dist;
		PHD_VECTOR last_pos;
		FX_INFO* spaz_effect;
		long mesh_effects;
		short* mesh_ptrs[15];
		ITEM_INFO* target;
		short target_angles[2];
		short turn_rate;
		short move_angle;
		short head_y_rot;
		short head_x_rot;
		short head_z_rot;
		short torso_y_rot;
		short torso_x_rot;
		short torso_z_rot;
		LARA_ARM left_arm;
		LARA_ARM right_arm;
		ushort holster;
		CREATURE_INFO* creature;
		long CornerX;
		long CornerZ;
		char RopeSegment;
		char RopeDirection;
		short RopeArcFront;
		short RopeArcBack;
		short RopeLastX;
		short RopeMaxXForward;
		short RopeMaxXBackward;
		long RopeDFrame;
		long RopeFrame;
		ushort RopeFrameRate;
		ushort RopeY;
		long RopePtr;
		void* GeneralPtr;
		long RopeOffset;
		ulong RopeDownVel;
		char RopeFlag;
		char MoveCount;
		long RopeCount;
		char pistols_type_carried;
		char uzis_type_carried;
		char shotgun_type_carried;
		char crossbow_type_carried;
		char grenade_type_carried;
		char sixshooter_type_carried;
		char lasersight;
		char binoculars;
		char crowbar;
		char mechanical_scarab;
		uchar small_water_skin;
		uchar big_water_skin;
		char examine1;
		char examine2;
		char examine3;
		char puzzleitems[12];
		ushort puzzleitemscombo;
		ushort keyitems;
		ushort keyitemscombo;
		ushort pickupitems;
		ushort pickupitemscombo;
		short questitems;
		short num_small_medipack;
		short num_large_medipack;
		short num_flares;
		short num_pistols_ammo;
		short num_uzi_ammo;
		short num_revolver_ammo;
		short num_shotgun_ammo1;
		short num_shotgun_ammo2;
		short num_grenade_ammo1;
		short num_grenade_ammo2;
		short num_grenade_ammo3;
		short num_crossbow_ammo1;
		short num_crossbow_ammo2;
		short num_crossbow_ammo3;
		char beetle_uses;
		char blindTimer;
		char location;
		char highest_location;
		char locationPad;
	};

	struct COLL_INFO
	{
		long mid_floor;
		long mid_ceiling;
		long mid_type;
		long front_floor;
		long front_ceiling;
		long front_type;
		long left_floor;
		long left_ceiling;
		long left_type;
		long right_floor;
		long right_ceiling;
		long right_type;
		long left_floor2;
		long left_ceiling2;
		long left_type2;
		long right_floor2;
		long right_ceiling2;
		long right_type2;
		long radius;
		long bad_pos;
		long bad_neg;
		long bad_ceiling;
		PHD_VECTOR shift;
		PHD_VECTOR old;
		short old_anim_state;
		short old_anim_number;
		short old_frame_number;
		short facing;
		short quadrant;
		short coll_type;
		short* trigger;
		char tilt_x;
		char tilt_z;
		char hit_by_baddie;
		char hit_static;
		ushort slopes_are_walls : 2;
		ushort slopes_are_pits : 1;
		ushort lava_is_pit : 1;
		ushort enable_baddie_push : 1;
		ushort enable_spaz : 1;
		ushort hit_ceiling : 1;
	};

	struct OBJECT_INFO
	{
		short nmeshes;
		short mesh_index;
		long bone_index;
		short* frame_base;
		void (*initialise)(short item_number);
		void (*control)(short item_number);
		void (*floor)(ITEM_INFO* item, long x, long y, long z, long* height);
		void (*ceiling)(ITEM_INFO* item, long x, long y, long z, long* height);
		void (*draw_routine)(ITEM_INFO* item);
		void (*collision)(short item_num, ITEM_INFO* laraitem, COLL_INFO* coll);
		short object_mip;
		short anim_index;
		short hit_points;
		short pivot_length;
		short radius;
		short shadow_size;
		ushort bite_offset;
		ushort loaded : 1;
		ushort intelligent : 1;
		ushort non_lot : 1;
		ushort save_position : 1;
		ushort save_hitpoints : 1;
		ushort save_flags : 1;
		ushort save_anim : 1;
		ushort semi_transparent : 1;
		ushort water_creature : 1;
		ushort using_drawanimating_item : 1;
		ushort HitEffect : 2;
		ushort undead : 1;
		ushort save_mesh : 1;
		void (*draw_routine_extra)(ITEM_INFO* item);
		ulong explodable_meshbits;
		ulong padfuck;
	};

	struct STATIC_INFO
	{
		short mesh_number;
		short flags;
		short x_minp;
		short x_maxp;
		short y_minp;
		short y_maxp;
		short z_minp;
		short z_maxp;
		short x_minc;
		short x_maxc;
		short y_minc;
		short y_maxc;
		short z_minc;
		short z_maxc;
	};

	struct CHANGE_STRUCT
	{
		short goal_anim_state;
		short number_ranges;
		short range_index;
	};

	struct RANGE_STRUCT
	{
		short start_frame;
		short end_frame;
		short link_anim_num;
		short link_frame_num;
	};

	struct ANIM_STRUCT
	{
		short* frame_ptr;
		short interpolation;
		short current_anim_state;
		long velocity;
		long acceleration;
		long Xvelocity;
		long Xacceleration;
		short frame_base;
		short frame_end;
		short jump_anim_num;
		short jump_frame_num;
		short number_changes;
		short change_index;
		short number_commands;
		short command_index;
	};

	struct FLOOR_INFO
	{
		ushort index;
		ushort fx : 4;
		ushort box : 11;
		ushort stopper : 1;
		uchar pit_room;
		char floor;
		uchar sky_room;
		char ceiling;
	};

	struct LIGHTINFO
	{
		long x;
		long y;
		long z;
		uchar r;
		uchar g;
		uchar b;
		uchar Type;
		short Intensity;
		float Inner;
		float Outer;
		float Length;
		float Cutoff;
		float nx;
		float ny;
		float nz;
	};

	struct MESH_INFO
	{
		long x;
		long y;
		long z;
		short y_rot;
		short shade;
		short Flags;
		short static_number;
	};

	struct PCLIGHT_INFO
	{
		float x;
		float y;
		float z;
		float r;
		float g;
		float b;
		long shadow;
		float Inner;
		float Outer;
		float InnerAngle;
		float OuterAngle;
		float Cutoff;
		float nx;
		float ny;
		float nz;
		long ix;
		long iy;
		long iz;
		long inx;
		long iny;
		long inz;
		uchar Type;
		uchar Pad;
	};

	struct ROOM_INFO
	{
		short* data;
		short* door;
		FLOOR_INFO* floor;
		LIGHTINFO* light;
		MESH_INFO* mesh;
		long x;
		long y;
		long z;
		long minfloor;
		long maxceiling;
		short x_size;
		short y_size;
		long ambient;
		short num_lights;
		short num_meshes;
		uchar ReverbType;
		uchar FlipNumber;
		char MeshEffect;
		char bound_active;
		short left;
		short right;
		short top;
		short bottom;
		short test_left;
		short test_right;
		short test_top;
		short test_bottom;
		short item_number;
		short fx_number;
		short flipped_room;
		ushort flags;
		long nVerts;
		long nWaterVerts;
		long nShoreVerts;
		LPDIRECT3DVERTEXBUFFER SourceVB;
		short* FaceData;
		float posx;
		float posy;
		float posz;
		D3DVECTOR* vnormals;
		D3DVECTOR* fnormals;
		long* prelight;
		long* prelightwater;
		long watercalc;
		D3DVECTOR* verts;
		long gt3cnt;
		long gt4cnt;
		PCLIGHT_INFO* pclight;
	};

	struct BIKEINFO
	{
		short right_front_wheelrot;
		short right_back_wheelrot;
		long left_wheelrot;
		long velocity;
		long unused1;
		long pitch1;
		short move_angle;
		short extra_rotation;
		short rot_thing;
		long bike_turn;
		long pitch2;
		short flags;
		short light_intensity;
	};

	struct JEEPINFO
	{
		short right_front_wheelrot;
		short left_front_wheelrot;
		short left_back_wheelrot;
		short right_back_wheelrot;
		long velocity;
		long unused1;
		long pitch1;
		long turn_rate;
		long camera_angle;
		short move_angle;
		short extra_rotation;
		short rot_thing;
		long pitch2;
		short flags;
		short unused2;
		short gear;
	};

	struct ROPE_STRUCT
	{
		PHD_VECTOR Segment[24];
		PHD_VECTOR Velocity[24];
		PHD_VECTOR NormalisedSegment[24];
		PHD_VECTOR MeshSegment[24];
		PHD_VECTOR Position;
		long Coords[24][3];
		long SegmentLength;
		long Active;
	};

	struct PENDULUM
	{
		PHD_VECTOR Position;
		PHD_VECTOR Velocity;
		long node;
		ROPE_STRUCT* Rope;
	};

	struct GAME_VECTOR
	{
		long x;
		long y;
		long z;
		short room_number;
		short box_number;
	};

	struct OBJECT_VECTOR
	{
		long x;
		long y;
		long z;
		short data;
		short flags;
	};

	struct CAMERA_INFO
	{
		GAME_VECTOR pos;
		GAME_VECTOR target;
		camera_type type;
		camera_type old_type;
		long shift;
		long flags;
		long fixed_camera;
		long number_frames;
		long bounce;
		long underwater;
		long target_distance;
		short target_angle;
		short target_elevation;
		short actual_elevation;
		short actual_angle;
		short number;
		short last;
		short timer;
		short speed;
		ITEM_INFO* item;
		ITEM_INFO* last_item;
		OBJECT_VECTOR* fixed;
		long mike_at_lara;
		PHD_VECTOR mike_pos;
	};

	struct SPOTCAM
	{
		long x;
		long y;
		long z;
		long tx;
		long ty;
		long tz;
		uchar sequence;
		uchar camera;
		short fov;
		short roll;
		short timer;
		short speed;
		short flags;
		short room_number;
		short pad;
	};

	struct SCARAB_STRUCT
	{
		PHD_3DPOS pos;
		short room_number;
		short speed;
		short fallspeed;
		uchar On;
		uchar flags;
	};

	struct DXDISPLAYMODE
	{
		long w;
		long h;
		long bpp;
		long RefreshRate;
		long bPalette;
		DDSURFACEDESC2 ddsd;
		uchar rbpp;
		uchar gbpp;
		uchar bbpp;
		uchar rshift;
		uchar gshift;
		uchar bshift;
	};

	struct DXTEXTUREINFO
	{
		DDPIXELFORMAT ddpf;
		ulong bpp;
		long bPalette;
		long bAlpha;
		uchar rbpp;
		uchar gbpp;
		uchar bbpp;
		uchar abpp;
		uchar rshift;
		uchar gshift;
		uchar bshift;
		uchar ashift;
	};

	struct DXZBUFFERINFO
	{
		DDPIXELFORMAT ddpf;
		ulong bpp;
	};

	struct DXD3DDEVICE
	{
		char Name[30];
		char About[80];
		LPGUID lpGuid;
		GUID Guid;
		D3DDEVICEDESC DeviceDesc;
		long bHardware;
		long nDisplayModes;
		DXDISPLAYMODE* DisplayModes;
		long nTextureInfos;
		DXTEXTUREINFO* TextureInfos;
		long nZBufferInfos;
		DXZBUFFERINFO* ZBufferInfos;
	};

	struct DXDIRECTDRAWINFO
	{
		char Name[30];
		char About[80];
		LPGUID lpGuid;
		GUID Guid;
		DDCAPS DDCaps;
		DDDEVICEIDENTIFIER DDIdentifier;
		int	 nDisplayModes;
		DXDISPLAYMODE* DisplayModes;
		int nD3DDevices;
		DXD3DDEVICE* D3DDevices;
	};

	struct DXDIRECTSOUNDINFO
	{
		char Name[30];
		char About[80];
		LPGUID lpGuid;
		GUID Guid;
	};

	struct DXINFO
	{
		long nDDInfo;
		long nDSInfo;
		DXDIRECTDRAWINFO* DDInfo;
		DXDIRECTSOUNDINFO* DSInfo;
		long nDD;
		long nD3D;
		long nDisplayMode;
		long nTexture;
		long nZBuffer;
		long nDS;
		bool bHardware;
	};

	struct DXPTR
	{
		LPDIRECTDRAW4 lpDD;
		LPDIRECT3D3 lpD3D;
		LPDIRECT3DDEVICE3 lpD3DDevice;
		LPDIRECT3DDEVICE3 _lpD3DDevice;
		LPDIRECTDRAWSURFACE4 lpPrimaryBuffer;
		LPDIRECTDRAWSURFACE4 lpBackBuffer;
		LPDIRECTDRAWSURFACE4 lpZBuffer;
		LPDIRECT3DVIEWPORT3 lpViewport;
		LPDIRECTSOUND lpDS;
		ulong dwRenderWidth;
		ulong dwRenderHeight;
		RECT rViewport;
		RECT rScreen;
		long Flags;
		long WindowStyle;
		long CoopLevel;
		LPDIRECTINPUT2 lpDirectInput;
		LPDIRECTINPUTDEVICE2 Keyboard;
		HWND hWnd;
		volatile long InScene;
		volatile long WaitAtBeginScene;
		volatile long DoneBlit;
	};

	struct WINAPP
	{
		HINSTANCE hInstance;
		HWND hWnd;
		WNDCLASS WindowClass;
		DXINFO DXInfo;
		DXPTR dx;
		HANDLE mutex;
		float fps;
		LPDIRECT3DMATERIAL3 GlobalMaterial;
		D3DMATERIALHANDLE GlobalMaterialHandle;
		HACCEL hAccel;
		bool SetupComplete;
		bool BumpMapping;
		long TextureSize;
		long BumpMapSize;
		bool mmx;
		bool Filtering;
		bool Volumetric;
		bool SoundDisabled;
		long StartFlags;
		volatile bool fmv;
		long Desktopbpp;
		long AutoTarget;
	};

	struct SoundSlot
	{
		long OrigVolume;
		long nVolume;
		long nPan;
		long nPitch;
		long nSampleInfo;
		ulong distance;
		PHD_VECTOR pos;
	};

	struct STATS
	{
		ulong Timer;
		ulong Distance;
		ulong AmmoUsed;
		ulong AmmoHits;
		ushort Kills;
		uchar Secrets;
		uchar HealthUsed;
	};

	struct CVECTOR
	{
		char b;
		char g;
		char r;
		char a;
	};

	struct SAVEGAME_INFO
	{
		LARA_INFO Lara;
		long cutscene_triggered;
		uchar HubLevels[10];	//saved level indices. highest one that isn't 0 is the one we are currently in
		ushort HubOffsets[10];	//offset of each level's data inside the savegame buffer
		ushort HubSizes[10];	//size of each level's data inside the savegame buffer
		char CurrentLevel;
		char Checksum;
		STATS Game;
		STATS Level;
		short WeaponObject;
		short WeaponAnim;
		short WeaponFrame;
		short WeaponCurrent;
		short WeaponGoal;
		CVECTOR fog_colour;
		uchar HubSavedLara : 1;	//flag that we saved Lara's data when we initialised hub, only set to 1 when InitialiseHub is called with 1
		uchar AutoTarget : 1;
		uchar HaveBikeBooster : 1;	//have the bike nitro thing
		char buffer[15410];
	};

	struct PISTOL_DEF
	{
		short ObjectNum;
		char Draw1Anim2;
		char Draw1Anim;
		char Draw2Anim;
		char RecoilAnim;
	};

	struct INVOBJ
	{
		short object_number;
		short yoff;
		short scale1;
		short yrot;
		short xrot;
		short zrot;
		short flags;
		short objname;
		ulong meshbits;
	};

	struct THREAD
	{
		volatile long active;
		long unk;
		volatile long ended;
		ulong handle;
		ulong address;
	};

	struct GAMEFLOW
	{
		union
		{
			struct
			{
				ulong CheatEnabled : 1;
				ulong LoadSaveEnabled : 1;
				ulong TitleEnabled : 1;
				ulong PlayAnyLevel : 1;
				ulong Language : 3;
				ulong DemoDisc : 1;
				ulong Unused : 24;
			};

			ulong bitfield;
		};

		ulong InputTimeout;
		uchar SecurityTag;
		uchar nLevels;
		uchar nFileNames;
		uchar Pad;
		ushort FileNameLen;
		ushort ScriptLen;
	};

	struct SORTLIST
	{
		float zVal;
		short drawtype;
		short tpage;
		short nVtx;
		short polytype;
	};

	struct SPHERE
	{
		long x;
		long y;
		long z;
		long r;
	};

	struct SHATTER_ITEM
	{
		SPHERE Sphere;
		ITEM_LIGHT* il;
		short* meshp;
		long Bit;
		short YRot;
		short Flags;
	};
#pragma pack(pop)
}
