name: Release Pipeline
on:
  release:
    types:
      - released
jobs:
  release:
    runs-on: windows-latest
    steps:
      - run: |
          curl -H 'Content-Type: application/json' (@'
          ${{ vars.RELEASE_MESSAGE }}
          '@ -f '${{ github.event.release.tag_name }}', @'
          ${{ github.event.release.body }}
          '@, '${{ github.event.release.assets[0].browser_download_url }}') ${{ secrets.RELEASE_WEBHOOK }}
